// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/artifact"
)

// ArtifactClient ...
type ArtifactClient interface {
	Options() artifact.Options
	GetAccountSettings(ctx context.Context, params *artifact.GetAccountSettingsInput, optFns ...func(*artifact.Options)) (*artifact.GetAccountSettingsOutput, error)
	GetReport(ctx context.Context, params *artifact.GetReportInput, optFns ...func(*artifact.Options)) (*artifact.GetReportOutput, error)
	GetReportMetadata(ctx context.Context, params *artifact.GetReportMetadataInput, optFns ...func(*artifact.Options)) (*artifact.GetReportMetadataOutput, error)
	GetTermForReport(ctx context.Context, params *artifact.GetTermForReportInput, optFns ...func(*artifact.Options)) (*artifact.GetTermForReportOutput, error)
	ListReports(ctx context.Context, params *artifact.ListReportsInput, optFns ...func(*artifact.Options)) (*artifact.ListReportsOutput, error)
	PutAccountSettings(ctx context.Context, params *artifact.PutAccountSettingsInput, optFns ...func(*artifact.Options)) (*artifact.PutAccountSettingsOutput, error)
}
