// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/autoscalingplans"
)

// AutoscalingplansClient ...
type AutoscalingplansClient interface {
	Options() autoscalingplans.Options
	CreateScalingPlan(ctx context.Context, params *autoscalingplans.CreateScalingPlanInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.CreateScalingPlanOutput, error)
	DeleteScalingPlan(ctx context.Context, params *autoscalingplans.DeleteScalingPlanInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.DeleteScalingPlanOutput, error)
	DescribeScalingPlanResources(ctx context.Context, params *autoscalingplans.DescribeScalingPlanResourcesInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.DescribeScalingPlanResourcesOutput, error)
	DescribeScalingPlans(ctx context.Context, params *autoscalingplans.DescribeScalingPlansInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.DescribeScalingPlansOutput, error)
	GetScalingPlanResourceForecastData(ctx context.Context, params *autoscalingplans.GetScalingPlanResourceForecastDataInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.GetScalingPlanResourceForecastDataOutput, error)
	UpdateScalingPlan(ctx context.Context, params *autoscalingplans.UpdateScalingPlanInput, optFns ...func(*autoscalingplans.Options)) (*autoscalingplans.UpdateScalingPlanOutput, error)
}
