// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/b2bi"
)

// B2biClient ...
type B2biClient interface {
	Options() b2bi.Options
	CreateCapability(ctx context.Context, params *b2bi.CreateCapabilityInput, optFns ...func(*b2bi.Options)) (*b2bi.CreateCapabilityOutput, error)
	CreatePartnership(ctx context.Context, params *b2bi.CreatePartnershipInput, optFns ...func(*b2bi.Options)) (*b2bi.CreatePartnershipOutput, error)
	CreateProfile(ctx context.Context, params *b2bi.CreateProfileInput, optFns ...func(*b2bi.Options)) (*b2bi.CreateProfileOutput, error)
	CreateTransformer(ctx context.Context, params *b2bi.CreateTransformerInput, optFns ...func(*b2bi.Options)) (*b2bi.CreateTransformerOutput, error)
	DeleteCapability(ctx context.Context, params *b2bi.DeleteCapabilityInput, optFns ...func(*b2bi.Options)) (*b2bi.DeleteCapabilityOutput, error)
	DeletePartnership(ctx context.Context, params *b2bi.DeletePartnershipInput, optFns ...func(*b2bi.Options)) (*b2bi.DeletePartnershipOutput, error)
	DeleteProfile(ctx context.Context, params *b2bi.DeleteProfileInput, optFns ...func(*b2bi.Options)) (*b2bi.DeleteProfileOutput, error)
	DeleteTransformer(ctx context.Context, params *b2bi.DeleteTransformerInput, optFns ...func(*b2bi.Options)) (*b2bi.DeleteTransformerOutput, error)
	GetCapability(ctx context.Context, params *b2bi.GetCapabilityInput, optFns ...func(*b2bi.Options)) (*b2bi.GetCapabilityOutput, error)
	GetPartnership(ctx context.Context, params *b2bi.GetPartnershipInput, optFns ...func(*b2bi.Options)) (*b2bi.GetPartnershipOutput, error)
	GetProfile(ctx context.Context, params *b2bi.GetProfileInput, optFns ...func(*b2bi.Options)) (*b2bi.GetProfileOutput, error)
	GetTransformer(ctx context.Context, params *b2bi.GetTransformerInput, optFns ...func(*b2bi.Options)) (*b2bi.GetTransformerOutput, error)
	GetTransformerJob(ctx context.Context, params *b2bi.GetTransformerJobInput, optFns ...func(*b2bi.Options)) (*b2bi.GetTransformerJobOutput, error)
	ListCapabilities(ctx context.Context, params *b2bi.ListCapabilitiesInput, optFns ...func(*b2bi.Options)) (*b2bi.ListCapabilitiesOutput, error)
	ListPartnerships(ctx context.Context, params *b2bi.ListPartnershipsInput, optFns ...func(*b2bi.Options)) (*b2bi.ListPartnershipsOutput, error)
	ListProfiles(ctx context.Context, params *b2bi.ListProfilesInput, optFns ...func(*b2bi.Options)) (*b2bi.ListProfilesOutput, error)
	ListTagsForResource(ctx context.Context, params *b2bi.ListTagsForResourceInput, optFns ...func(*b2bi.Options)) (*b2bi.ListTagsForResourceOutput, error)
	ListTransformers(ctx context.Context, params *b2bi.ListTransformersInput, optFns ...func(*b2bi.Options)) (*b2bi.ListTransformersOutput, error)
	StartTransformerJob(ctx context.Context, params *b2bi.StartTransformerJobInput, optFns ...func(*b2bi.Options)) (*b2bi.StartTransformerJobOutput, error)
	TagResource(ctx context.Context, params *b2bi.TagResourceInput, optFns ...func(*b2bi.Options)) (*b2bi.TagResourceOutput, error)
	TestMapping(ctx context.Context, params *b2bi.TestMappingInput, optFns ...func(*b2bi.Options)) (*b2bi.TestMappingOutput, error)
	TestParsing(ctx context.Context, params *b2bi.TestParsingInput, optFns ...func(*b2bi.Options)) (*b2bi.TestParsingOutput, error)
	UntagResource(ctx context.Context, params *b2bi.UntagResourceInput, optFns ...func(*b2bi.Options)) (*b2bi.UntagResourceOutput, error)
	UpdateCapability(ctx context.Context, params *b2bi.UpdateCapabilityInput, optFns ...func(*b2bi.Options)) (*b2bi.UpdateCapabilityOutput, error)
	UpdatePartnership(ctx context.Context, params *b2bi.UpdatePartnershipInput, optFns ...func(*b2bi.Options)) (*b2bi.UpdatePartnershipOutput, error)
	UpdateProfile(ctx context.Context, params *b2bi.UpdateProfileInput, optFns ...func(*b2bi.Options)) (*b2bi.UpdateProfileOutput, error)
	UpdateTransformer(ctx context.Context, params *b2bi.UpdateTransformerInput, optFns ...func(*b2bi.Options)) (*b2bi.UpdateTransformerOutput, error)
}
