// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/billingconductor"
)

// BillingconductorClient ...
type BillingconductorClient interface {
	Options() billingconductor.Options
	AssociateAccounts(ctx context.Context, params *billingconductor.AssociateAccountsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.AssociateAccountsOutput, error)
	AssociatePricingRules(ctx context.Context, params *billingconductor.AssociatePricingRulesInput, optFns ...func(*billingconductor.Options)) (*billingconductor.AssociatePricingRulesOutput, error)
	BatchAssociateResourcesToCustomLineItem(ctx context.Context, params *billingconductor.BatchAssociateResourcesToCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.BatchAssociateResourcesToCustomLineItemOutput, error)
	BatchDisassociateResourcesFromCustomLineItem(ctx context.Context, params *billingconductor.BatchDisassociateResourcesFromCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.BatchDisassociateResourcesFromCustomLineItemOutput, error)
	CreateBillingGroup(ctx context.Context, params *billingconductor.CreateBillingGroupInput, optFns ...func(*billingconductor.Options)) (*billingconductor.CreateBillingGroupOutput, error)
	CreateCustomLineItem(ctx context.Context, params *billingconductor.CreateCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.CreateCustomLineItemOutput, error)
	CreatePricingPlan(ctx context.Context, params *billingconductor.CreatePricingPlanInput, optFns ...func(*billingconductor.Options)) (*billingconductor.CreatePricingPlanOutput, error)
	CreatePricingRule(ctx context.Context, params *billingconductor.CreatePricingRuleInput, optFns ...func(*billingconductor.Options)) (*billingconductor.CreatePricingRuleOutput, error)
	DeleteBillingGroup(ctx context.Context, params *billingconductor.DeleteBillingGroupInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DeleteBillingGroupOutput, error)
	DeleteCustomLineItem(ctx context.Context, params *billingconductor.DeleteCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DeleteCustomLineItemOutput, error)
	DeletePricingPlan(ctx context.Context, params *billingconductor.DeletePricingPlanInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DeletePricingPlanOutput, error)
	DeletePricingRule(ctx context.Context, params *billingconductor.DeletePricingRuleInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DeletePricingRuleOutput, error)
	DisassociateAccounts(ctx context.Context, params *billingconductor.DisassociateAccountsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DisassociateAccountsOutput, error)
	DisassociatePricingRules(ctx context.Context, params *billingconductor.DisassociatePricingRulesInput, optFns ...func(*billingconductor.Options)) (*billingconductor.DisassociatePricingRulesOutput, error)
	GetBillingGroupCostReport(ctx context.Context, params *billingconductor.GetBillingGroupCostReportInput, optFns ...func(*billingconductor.Options)) (*billingconductor.GetBillingGroupCostReportOutput, error)
	ListAccountAssociations(ctx context.Context, params *billingconductor.ListAccountAssociationsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListAccountAssociationsOutput, error)
	ListBillingGroupCostReports(ctx context.Context, params *billingconductor.ListBillingGroupCostReportsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListBillingGroupCostReportsOutput, error)
	ListBillingGroups(ctx context.Context, params *billingconductor.ListBillingGroupsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListBillingGroupsOutput, error)
	ListCustomLineItemVersions(ctx context.Context, params *billingconductor.ListCustomLineItemVersionsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListCustomLineItemVersionsOutput, error)
	ListCustomLineItems(ctx context.Context, params *billingconductor.ListCustomLineItemsInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListCustomLineItemsOutput, error)
	ListPricingPlans(ctx context.Context, params *billingconductor.ListPricingPlansInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListPricingPlansOutput, error)
	ListPricingPlansAssociatedWithPricingRule(ctx context.Context, params *billingconductor.ListPricingPlansAssociatedWithPricingRuleInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListPricingPlansAssociatedWithPricingRuleOutput, error)
	ListPricingRules(ctx context.Context, params *billingconductor.ListPricingRulesInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListPricingRulesOutput, error)
	ListPricingRulesAssociatedToPricingPlan(ctx context.Context, params *billingconductor.ListPricingRulesAssociatedToPricingPlanInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListPricingRulesAssociatedToPricingPlanOutput, error)
	ListResourcesAssociatedToCustomLineItem(ctx context.Context, params *billingconductor.ListResourcesAssociatedToCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListResourcesAssociatedToCustomLineItemOutput, error)
	ListTagsForResource(ctx context.Context, params *billingconductor.ListTagsForResourceInput, optFns ...func(*billingconductor.Options)) (*billingconductor.ListTagsForResourceOutput, error)
	TagResource(ctx context.Context, params *billingconductor.TagResourceInput, optFns ...func(*billingconductor.Options)) (*billingconductor.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *billingconductor.UntagResourceInput, optFns ...func(*billingconductor.Options)) (*billingconductor.UntagResourceOutput, error)
	UpdateBillingGroup(ctx context.Context, params *billingconductor.UpdateBillingGroupInput, optFns ...func(*billingconductor.Options)) (*billingconductor.UpdateBillingGroupOutput, error)
	UpdateCustomLineItem(ctx context.Context, params *billingconductor.UpdateCustomLineItemInput, optFns ...func(*billingconductor.Options)) (*billingconductor.UpdateCustomLineItemOutput, error)
	UpdatePricingPlan(ctx context.Context, params *billingconductor.UpdatePricingPlanInput, optFns ...func(*billingconductor.Options)) (*billingconductor.UpdatePricingPlanOutput, error)
	UpdatePricingRule(ctx context.Context, params *billingconductor.UpdatePricingRuleInput, optFns ...func(*billingconductor.Options)) (*billingconductor.UpdatePricingRuleOutput, error)
}
