// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines"
)

// ChimesdkmediapipelinesClient ...
type ChimesdkmediapipelinesClient interface {
	Options() chimesdkmediapipelines.Options
	CreateMediaCapturePipeline(ctx context.Context, params *chimesdkmediapipelines.CreateMediaCapturePipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaCapturePipelineOutput, error)
	CreateMediaConcatenationPipeline(ctx context.Context, params *chimesdkmediapipelines.CreateMediaConcatenationPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaConcatenationPipelineOutput, error)
	CreateMediaInsightsPipeline(ctx context.Context, params *chimesdkmediapipelines.CreateMediaInsightsPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaInsightsPipelineOutput, error)
	CreateMediaInsightsPipelineConfiguration(ctx context.Context, params *chimesdkmediapipelines.CreateMediaInsightsPipelineConfigurationInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaInsightsPipelineConfigurationOutput, error)
	CreateMediaLiveConnectorPipeline(ctx context.Context, params *chimesdkmediapipelines.CreateMediaLiveConnectorPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaLiveConnectorPipelineOutput, error)
	CreateMediaPipelineKinesisVideoStreamPool(ctx context.Context, params *chimesdkmediapipelines.CreateMediaPipelineKinesisVideoStreamPoolInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaPipelineKinesisVideoStreamPoolOutput, error)
	CreateMediaStreamPipeline(ctx context.Context, params *chimesdkmediapipelines.CreateMediaStreamPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.CreateMediaStreamPipelineOutput, error)
	DeleteMediaCapturePipeline(ctx context.Context, params *chimesdkmediapipelines.DeleteMediaCapturePipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.DeleteMediaCapturePipelineOutput, error)
	DeleteMediaInsightsPipelineConfiguration(ctx context.Context, params *chimesdkmediapipelines.DeleteMediaInsightsPipelineConfigurationInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.DeleteMediaInsightsPipelineConfigurationOutput, error)
	DeleteMediaPipeline(ctx context.Context, params *chimesdkmediapipelines.DeleteMediaPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.DeleteMediaPipelineOutput, error)
	DeleteMediaPipelineKinesisVideoStreamPool(ctx context.Context, params *chimesdkmediapipelines.DeleteMediaPipelineKinesisVideoStreamPoolInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.DeleteMediaPipelineKinesisVideoStreamPoolOutput, error)
	GetMediaCapturePipeline(ctx context.Context, params *chimesdkmediapipelines.GetMediaCapturePipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetMediaCapturePipelineOutput, error)
	GetMediaInsightsPipelineConfiguration(ctx context.Context, params *chimesdkmediapipelines.GetMediaInsightsPipelineConfigurationInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetMediaInsightsPipelineConfigurationOutput, error)
	GetMediaPipeline(ctx context.Context, params *chimesdkmediapipelines.GetMediaPipelineInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetMediaPipelineOutput, error)
	GetMediaPipelineKinesisVideoStreamPool(ctx context.Context, params *chimesdkmediapipelines.GetMediaPipelineKinesisVideoStreamPoolInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetMediaPipelineKinesisVideoStreamPoolOutput, error)
	GetSpeakerSearchTask(ctx context.Context, params *chimesdkmediapipelines.GetSpeakerSearchTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetSpeakerSearchTaskOutput, error)
	GetVoiceToneAnalysisTask(ctx context.Context, params *chimesdkmediapipelines.GetVoiceToneAnalysisTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.GetVoiceToneAnalysisTaskOutput, error)
	ListMediaCapturePipelines(ctx context.Context, params *chimesdkmediapipelines.ListMediaCapturePipelinesInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.ListMediaCapturePipelinesOutput, error)
	ListMediaInsightsPipelineConfigurations(ctx context.Context, params *chimesdkmediapipelines.ListMediaInsightsPipelineConfigurationsInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.ListMediaInsightsPipelineConfigurationsOutput, error)
	ListMediaPipelineKinesisVideoStreamPools(ctx context.Context, params *chimesdkmediapipelines.ListMediaPipelineKinesisVideoStreamPoolsInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.ListMediaPipelineKinesisVideoStreamPoolsOutput, error)
	ListMediaPipelines(ctx context.Context, params *chimesdkmediapipelines.ListMediaPipelinesInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.ListMediaPipelinesOutput, error)
	ListTagsForResource(ctx context.Context, params *chimesdkmediapipelines.ListTagsForResourceInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.ListTagsForResourceOutput, error)
	StartSpeakerSearchTask(ctx context.Context, params *chimesdkmediapipelines.StartSpeakerSearchTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.StartSpeakerSearchTaskOutput, error)
	StartVoiceToneAnalysisTask(ctx context.Context, params *chimesdkmediapipelines.StartVoiceToneAnalysisTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.StartVoiceToneAnalysisTaskOutput, error)
	StopSpeakerSearchTask(ctx context.Context, params *chimesdkmediapipelines.StopSpeakerSearchTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.StopSpeakerSearchTaskOutput, error)
	StopVoiceToneAnalysisTask(ctx context.Context, params *chimesdkmediapipelines.StopVoiceToneAnalysisTaskInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.StopVoiceToneAnalysisTaskOutput, error)
	TagResource(ctx context.Context, params *chimesdkmediapipelines.TagResourceInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *chimesdkmediapipelines.UntagResourceInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.UntagResourceOutput, error)
	UpdateMediaInsightsPipelineConfiguration(ctx context.Context, params *chimesdkmediapipelines.UpdateMediaInsightsPipelineConfigurationInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.UpdateMediaInsightsPipelineConfigurationOutput, error)
	UpdateMediaInsightsPipelineStatus(ctx context.Context, params *chimesdkmediapipelines.UpdateMediaInsightsPipelineStatusInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.UpdateMediaInsightsPipelineStatusOutput, error)
	UpdateMediaPipelineKinesisVideoStreamPool(ctx context.Context, params *chimesdkmediapipelines.UpdateMediaPipelineKinesisVideoStreamPoolInput, optFns ...func(*chimesdkmediapipelines.Options)) (*chimesdkmediapipelines.UpdateMediaPipelineKinesisVideoStreamPoolOutput, error)
}
