// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloud9"
)

// Cloud9Client ...
type Cloud9Client interface {
	Options() cloud9.Options
	CreateEnvironmentEC2(ctx context.Context, params *cloud9.CreateEnvironmentEC2Input, optFns ...func(*cloud9.Options)) (*cloud9.CreateEnvironmentEC2Output, error)
	CreateEnvironmentMembership(ctx context.Context, params *cloud9.CreateEnvironmentMembershipInput, optFns ...func(*cloud9.Options)) (*cloud9.CreateEnvironmentMembershipOutput, error)
	DeleteEnvironment(ctx context.Context, params *cloud9.DeleteEnvironmentInput, optFns ...func(*cloud9.Options)) (*cloud9.DeleteEnvironmentOutput, error)
	DeleteEnvironmentMembership(ctx context.Context, params *cloud9.DeleteEnvironmentMembershipInput, optFns ...func(*cloud9.Options)) (*cloud9.DeleteEnvironmentMembershipOutput, error)
	DescribeEnvironmentMemberships(ctx context.Context, params *cloud9.DescribeEnvironmentMembershipsInput, optFns ...func(*cloud9.Options)) (*cloud9.DescribeEnvironmentMembershipsOutput, error)
	DescribeEnvironmentStatus(ctx context.Context, params *cloud9.DescribeEnvironmentStatusInput, optFns ...func(*cloud9.Options)) (*cloud9.DescribeEnvironmentStatusOutput, error)
	DescribeEnvironments(ctx context.Context, params *cloud9.DescribeEnvironmentsInput, optFns ...func(*cloud9.Options)) (*cloud9.DescribeEnvironmentsOutput, error)
	ListEnvironments(ctx context.Context, params *cloud9.ListEnvironmentsInput, optFns ...func(*cloud9.Options)) (*cloud9.ListEnvironmentsOutput, error)
	ListTagsForResource(ctx context.Context, params *cloud9.ListTagsForResourceInput, optFns ...func(*cloud9.Options)) (*cloud9.ListTagsForResourceOutput, error)
	TagResource(ctx context.Context, params *cloud9.TagResourceInput, optFns ...func(*cloud9.Options)) (*cloud9.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *cloud9.UntagResourceInput, optFns ...func(*cloud9.Options)) (*cloud9.UntagResourceOutput, error)
	UpdateEnvironment(ctx context.Context, params *cloud9.UpdateEnvironmentInput, optFns ...func(*cloud9.Options)) (*cloud9.UpdateEnvironmentOutput, error)
	UpdateEnvironmentMembership(ctx context.Context, params *cloud9.UpdateEnvironmentMembershipInput, optFns ...func(*cloud9.Options)) (*cloud9.UpdateEnvironmentMembershipOutput, error)
}
