// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudhsm"
)

// CloudhsmClient ...
type CloudhsmClient interface {
	Options() cloudhsm.Options
	AddTagsToResource(ctx context.Context, params *cloudhsm.AddTagsToResourceInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.AddTagsToResourceOutput, error)
	CreateHapg(ctx context.Context, params *cloudhsm.CreateHapgInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.CreateHapgOutput, error)
	CreateHsm(ctx context.Context, params *cloudhsm.CreateHsmInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.CreateHsmOutput, error)
	CreateLunaClient(ctx context.Context, params *cloudhsm.CreateLunaClientInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.CreateLunaClientOutput, error)
	DeleteHapg(ctx context.Context, params *cloudhsm.DeleteHapgInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DeleteHapgOutput, error)
	DeleteHsm(ctx context.Context, params *cloudhsm.DeleteHsmInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DeleteHsmOutput, error)
	DeleteLunaClient(ctx context.Context, params *cloudhsm.DeleteLunaClientInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DeleteLunaClientOutput, error)
	DescribeHapg(ctx context.Context, params *cloudhsm.DescribeHapgInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DescribeHapgOutput, error)
	DescribeHsm(ctx context.Context, params *cloudhsm.DescribeHsmInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DescribeHsmOutput, error)
	DescribeLunaClient(ctx context.Context, params *cloudhsm.DescribeLunaClientInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.DescribeLunaClientOutput, error)
	GetConfig(ctx context.Context, params *cloudhsm.GetConfigInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.GetConfigOutput, error)
	ListAvailableZones(ctx context.Context, params *cloudhsm.ListAvailableZonesInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ListAvailableZonesOutput, error)
	ListHapgs(ctx context.Context, params *cloudhsm.ListHapgsInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ListHapgsOutput, error)
	ListHsms(ctx context.Context, params *cloudhsm.ListHsmsInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ListHsmsOutput, error)
	ListLunaClients(ctx context.Context, params *cloudhsm.ListLunaClientsInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ListLunaClientsOutput, error)
	ListTagsForResource(ctx context.Context, params *cloudhsm.ListTagsForResourceInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ListTagsForResourceOutput, error)
	ModifyHapg(ctx context.Context, params *cloudhsm.ModifyHapgInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ModifyHapgOutput, error)
	ModifyHsm(ctx context.Context, params *cloudhsm.ModifyHsmInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ModifyHsmOutput, error)
	ModifyLunaClient(ctx context.Context, params *cloudhsm.ModifyLunaClientInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.ModifyLunaClientOutput, error)
	RemoveTagsFromResource(ctx context.Context, params *cloudhsm.RemoveTagsFromResourceInput, optFns ...func(*cloudhsm.Options)) (*cloudhsm.RemoveTagsFromResourceOutput, error)
}
