// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/codepipeline"
)

// CodepipelineClient ...
type CodepipelineClient interface {
	Options() codepipeline.Options
	AcknowledgeJob(ctx context.Context, params *codepipeline.AcknowledgeJobInput, optFns ...func(*codepipeline.Options)) (*codepipeline.AcknowledgeJobOutput, error)
	AcknowledgeThirdPartyJob(ctx context.Context, params *codepipeline.AcknowledgeThirdPartyJobInput, optFns ...func(*codepipeline.Options)) (*codepipeline.AcknowledgeThirdPartyJobOutput, error)
	CreateCustomActionType(ctx context.Context, params *codepipeline.CreateCustomActionTypeInput, optFns ...func(*codepipeline.Options)) (*codepipeline.CreateCustomActionTypeOutput, error)
	CreatePipeline(ctx context.Context, params *codepipeline.CreatePipelineInput, optFns ...func(*codepipeline.Options)) (*codepipeline.CreatePipelineOutput, error)
	DeleteCustomActionType(ctx context.Context, params *codepipeline.DeleteCustomActionTypeInput, optFns ...func(*codepipeline.Options)) (*codepipeline.DeleteCustomActionTypeOutput, error)
	DeletePipeline(ctx context.Context, params *codepipeline.DeletePipelineInput, optFns ...func(*codepipeline.Options)) (*codepipeline.DeletePipelineOutput, error)
	DeleteWebhook(ctx context.Context, params *codepipeline.DeleteWebhookInput, optFns ...func(*codepipeline.Options)) (*codepipeline.DeleteWebhookOutput, error)
	DeregisterWebhookWithThirdParty(ctx context.Context, params *codepipeline.DeregisterWebhookWithThirdPartyInput, optFns ...func(*codepipeline.Options)) (*codepipeline.DeregisterWebhookWithThirdPartyOutput, error)
	DisableStageTransition(ctx context.Context, params *codepipeline.DisableStageTransitionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.DisableStageTransitionOutput, error)
	EnableStageTransition(ctx context.Context, params *codepipeline.EnableStageTransitionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.EnableStageTransitionOutput, error)
	GetActionType(ctx context.Context, params *codepipeline.GetActionTypeInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetActionTypeOutput, error)
	GetJobDetails(ctx context.Context, params *codepipeline.GetJobDetailsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetJobDetailsOutput, error)
	GetPipeline(ctx context.Context, params *codepipeline.GetPipelineInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetPipelineOutput, error)
	GetPipelineExecution(ctx context.Context, params *codepipeline.GetPipelineExecutionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetPipelineExecutionOutput, error)
	GetPipelineState(ctx context.Context, params *codepipeline.GetPipelineStateInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetPipelineStateOutput, error)
	GetThirdPartyJobDetails(ctx context.Context, params *codepipeline.GetThirdPartyJobDetailsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.GetThirdPartyJobDetailsOutput, error)
	ListActionExecutions(ctx context.Context, params *codepipeline.ListActionExecutionsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListActionExecutionsOutput, error)
	ListActionTypes(ctx context.Context, params *codepipeline.ListActionTypesInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListActionTypesOutput, error)
	ListPipelineExecutions(ctx context.Context, params *codepipeline.ListPipelineExecutionsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListPipelineExecutionsOutput, error)
	ListPipelines(ctx context.Context, params *codepipeline.ListPipelinesInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListPipelinesOutput, error)
	ListTagsForResource(ctx context.Context, params *codepipeline.ListTagsForResourceInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListTagsForResourceOutput, error)
	ListWebhooks(ctx context.Context, params *codepipeline.ListWebhooksInput, optFns ...func(*codepipeline.Options)) (*codepipeline.ListWebhooksOutput, error)
	PollForJobs(ctx context.Context, params *codepipeline.PollForJobsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PollForJobsOutput, error)
	PollForThirdPartyJobs(ctx context.Context, params *codepipeline.PollForThirdPartyJobsInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PollForThirdPartyJobsOutput, error)
	PutActionRevision(ctx context.Context, params *codepipeline.PutActionRevisionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutActionRevisionOutput, error)
	PutApprovalResult(ctx context.Context, params *codepipeline.PutApprovalResultInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutApprovalResultOutput, error)
	PutJobFailureResult(ctx context.Context, params *codepipeline.PutJobFailureResultInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutJobFailureResultOutput, error)
	PutJobSuccessResult(ctx context.Context, params *codepipeline.PutJobSuccessResultInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutJobSuccessResultOutput, error)
	PutThirdPartyJobFailureResult(ctx context.Context, params *codepipeline.PutThirdPartyJobFailureResultInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutThirdPartyJobFailureResultOutput, error)
	PutThirdPartyJobSuccessResult(ctx context.Context, params *codepipeline.PutThirdPartyJobSuccessResultInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutThirdPartyJobSuccessResultOutput, error)
	PutWebhook(ctx context.Context, params *codepipeline.PutWebhookInput, optFns ...func(*codepipeline.Options)) (*codepipeline.PutWebhookOutput, error)
	RegisterWebhookWithThirdParty(ctx context.Context, params *codepipeline.RegisterWebhookWithThirdPartyInput, optFns ...func(*codepipeline.Options)) (*codepipeline.RegisterWebhookWithThirdPartyOutput, error)
	RetryStageExecution(ctx context.Context, params *codepipeline.RetryStageExecutionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.RetryStageExecutionOutput, error)
	StartPipelineExecution(ctx context.Context, params *codepipeline.StartPipelineExecutionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.StartPipelineExecutionOutput, error)
	StopPipelineExecution(ctx context.Context, params *codepipeline.StopPipelineExecutionInput, optFns ...func(*codepipeline.Options)) (*codepipeline.StopPipelineExecutionOutput, error)
	TagResource(ctx context.Context, params *codepipeline.TagResourceInput, optFns ...func(*codepipeline.Options)) (*codepipeline.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *codepipeline.UntagResourceInput, optFns ...func(*codepipeline.Options)) (*codepipeline.UntagResourceOutput, error)
	UpdateActionType(ctx context.Context, params *codepipeline.UpdateActionTypeInput, optFns ...func(*codepipeline.Options)) (*codepipeline.UpdateActionTypeOutput, error)
	UpdatePipeline(ctx context.Context, params *codepipeline.UpdatePipelineInput, optFns ...func(*codepipeline.Options)) (*codepipeline.UpdatePipelineOutput, error)
}
