// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/codeguruprofiler"
)

// CodeguruprofilerClient ...
type CodeguruprofilerClient interface {
	Options() codeguruprofiler.Options
	AddNotificationChannels(ctx context.Context, params *codeguruprofiler.AddNotificationChannelsInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.AddNotificationChannelsOutput, error)
	BatchGetFrameMetricData(ctx context.Context, params *codeguruprofiler.BatchGetFrameMetricDataInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.BatchGetFrameMetricDataOutput, error)
	ConfigureAgent(ctx context.Context, params *codeguruprofiler.ConfigureAgentInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.ConfigureAgentOutput, error)
	CreateProfilingGroup(ctx context.Context, params *codeguruprofiler.CreateProfilingGroupInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.CreateProfilingGroupOutput, error)
	DeleteProfilingGroup(ctx context.Context, params *codeguruprofiler.DeleteProfilingGroupInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.DeleteProfilingGroupOutput, error)
	DescribeProfilingGroup(ctx context.Context, params *codeguruprofiler.DescribeProfilingGroupInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.DescribeProfilingGroupOutput, error)
	GetFindingsReportAccountSummary(ctx context.Context, params *codeguruprofiler.GetFindingsReportAccountSummaryInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.GetFindingsReportAccountSummaryOutput, error)
	GetNotificationConfiguration(ctx context.Context, params *codeguruprofiler.GetNotificationConfigurationInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.GetNotificationConfigurationOutput, error)
	GetPolicy(ctx context.Context, params *codeguruprofiler.GetPolicyInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.GetPolicyOutput, error)
	GetProfile(ctx context.Context, params *codeguruprofiler.GetProfileInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.GetProfileOutput, error)
	GetRecommendations(ctx context.Context, params *codeguruprofiler.GetRecommendationsInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.GetRecommendationsOutput, error)
	ListFindingsReports(ctx context.Context, params *codeguruprofiler.ListFindingsReportsInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.ListFindingsReportsOutput, error)
	ListProfileTimes(ctx context.Context, params *codeguruprofiler.ListProfileTimesInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.ListProfileTimesOutput, error)
	ListProfilingGroups(ctx context.Context, params *codeguruprofiler.ListProfilingGroupsInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.ListProfilingGroupsOutput, error)
	ListTagsForResource(ctx context.Context, params *codeguruprofiler.ListTagsForResourceInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.ListTagsForResourceOutput, error)
	PostAgentProfile(ctx context.Context, params *codeguruprofiler.PostAgentProfileInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.PostAgentProfileOutput, error)
	PutPermission(ctx context.Context, params *codeguruprofiler.PutPermissionInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.PutPermissionOutput, error)
	RemoveNotificationChannel(ctx context.Context, params *codeguruprofiler.RemoveNotificationChannelInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.RemoveNotificationChannelOutput, error)
	RemovePermission(ctx context.Context, params *codeguruprofiler.RemovePermissionInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.RemovePermissionOutput, error)
	SubmitFeedback(ctx context.Context, params *codeguruprofiler.SubmitFeedbackInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.SubmitFeedbackOutput, error)
	TagResource(ctx context.Context, params *codeguruprofiler.TagResourceInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *codeguruprofiler.UntagResourceInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.UntagResourceOutput, error)
	UpdateProfilingGroup(ctx context.Context, params *codeguruprofiler.UpdateProfilingGroupInput, optFns ...func(*codeguruprofiler.Options)) (*codeguruprofiler.UpdateProfilingGroupOutput, error)
}
