// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cognitoidentity"
)

// CognitoidentityClient ...
type CognitoidentityClient interface {
	Options() cognitoidentity.Options
	CreateIdentityPool(ctx context.Context, params *cognitoidentity.CreateIdentityPoolInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.CreateIdentityPoolOutput, error)
	DeleteIdentities(ctx context.Context, params *cognitoidentity.DeleteIdentitiesInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.DeleteIdentitiesOutput, error)
	DeleteIdentityPool(ctx context.Context, params *cognitoidentity.DeleteIdentityPoolInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.DeleteIdentityPoolOutput, error)
	DescribeIdentity(ctx context.Context, params *cognitoidentity.DescribeIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.DescribeIdentityOutput, error)
	DescribeIdentityPool(ctx context.Context, params *cognitoidentity.DescribeIdentityPoolInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.DescribeIdentityPoolOutput, error)
	GetCredentialsForIdentity(ctx context.Context, params *cognitoidentity.GetCredentialsForIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetCredentialsForIdentityOutput, error)
	GetId(ctx context.Context, params *cognitoidentity.GetIdInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetIdOutput, error)
	GetIdentityPoolRoles(ctx context.Context, params *cognitoidentity.GetIdentityPoolRolesInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetIdentityPoolRolesOutput, error)
	GetOpenIdToken(ctx context.Context, params *cognitoidentity.GetOpenIdTokenInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetOpenIdTokenOutput, error)
	GetOpenIdTokenForDeveloperIdentity(ctx context.Context, params *cognitoidentity.GetOpenIdTokenForDeveloperIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetOpenIdTokenForDeveloperIdentityOutput, error)
	GetPrincipalTagAttributeMap(ctx context.Context, params *cognitoidentity.GetPrincipalTagAttributeMapInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.GetPrincipalTagAttributeMapOutput, error)
	ListIdentities(ctx context.Context, params *cognitoidentity.ListIdentitiesInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.ListIdentitiesOutput, error)
	ListIdentityPools(ctx context.Context, params *cognitoidentity.ListIdentityPoolsInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.ListIdentityPoolsOutput, error)
	ListTagsForResource(ctx context.Context, params *cognitoidentity.ListTagsForResourceInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.ListTagsForResourceOutput, error)
	LookupDeveloperIdentity(ctx context.Context, params *cognitoidentity.LookupDeveloperIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.LookupDeveloperIdentityOutput, error)
	MergeDeveloperIdentities(ctx context.Context, params *cognitoidentity.MergeDeveloperIdentitiesInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.MergeDeveloperIdentitiesOutput, error)
	SetIdentityPoolRoles(ctx context.Context, params *cognitoidentity.SetIdentityPoolRolesInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.SetIdentityPoolRolesOutput, error)
	SetPrincipalTagAttributeMap(ctx context.Context, params *cognitoidentity.SetPrincipalTagAttributeMapInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.SetPrincipalTagAttributeMapOutput, error)
	TagResource(ctx context.Context, params *cognitoidentity.TagResourceInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.TagResourceOutput, error)
	UnlinkDeveloperIdentity(ctx context.Context, params *cognitoidentity.UnlinkDeveloperIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.UnlinkDeveloperIdentityOutput, error)
	UnlinkIdentity(ctx context.Context, params *cognitoidentity.UnlinkIdentityInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.UnlinkIdentityOutput, error)
	UntagResource(ctx context.Context, params *cognitoidentity.UntagResourceInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.UntagResourceOutput, error)
	UpdateIdentityPool(ctx context.Context, params *cognitoidentity.UpdateIdentityPoolInput, optFns ...func(*cognitoidentity.Options)) (*cognitoidentity.UpdateIdentityPoolOutput, error)
}
