// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/computeoptimizer"
)

// ComputeoptimizerClient ...
type ComputeoptimizerClient interface {
	Options() computeoptimizer.Options
	DeleteRecommendationPreferences(ctx context.Context, params *computeoptimizer.DeleteRecommendationPreferencesInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.DeleteRecommendationPreferencesOutput, error)
	DescribeRecommendationExportJobs(ctx context.Context, params *computeoptimizer.DescribeRecommendationExportJobsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.DescribeRecommendationExportJobsOutput, error)
	ExportAutoScalingGroupRecommendations(ctx context.Context, params *computeoptimizer.ExportAutoScalingGroupRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportAutoScalingGroupRecommendationsOutput, error)
	ExportEBSVolumeRecommendations(ctx context.Context, params *computeoptimizer.ExportEBSVolumeRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportEBSVolumeRecommendationsOutput, error)
	ExportEC2InstanceRecommendations(ctx context.Context, params *computeoptimizer.ExportEC2InstanceRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportEC2InstanceRecommendationsOutput, error)
	ExportECSServiceRecommendations(ctx context.Context, params *computeoptimizer.ExportECSServiceRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportECSServiceRecommendationsOutput, error)
	ExportLambdaFunctionRecommendations(ctx context.Context, params *computeoptimizer.ExportLambdaFunctionRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportLambdaFunctionRecommendationsOutput, error)
	ExportLicenseRecommendations(ctx context.Context, params *computeoptimizer.ExportLicenseRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.ExportLicenseRecommendationsOutput, error)
	GetAutoScalingGroupRecommendations(ctx context.Context, params *computeoptimizer.GetAutoScalingGroupRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetAutoScalingGroupRecommendationsOutput, error)
	GetEBSVolumeRecommendations(ctx context.Context, params *computeoptimizer.GetEBSVolumeRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEBSVolumeRecommendationsOutput, error)
	GetEC2InstanceRecommendations(ctx context.Context, params *computeoptimizer.GetEC2InstanceRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEC2InstanceRecommendationsOutput, error)
	GetEC2RecommendationProjectedMetrics(ctx context.Context, params *computeoptimizer.GetEC2RecommendationProjectedMetricsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEC2RecommendationProjectedMetricsOutput, error)
	GetECSServiceRecommendationProjectedMetrics(ctx context.Context, params *computeoptimizer.GetECSServiceRecommendationProjectedMetricsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetECSServiceRecommendationProjectedMetricsOutput, error)
	GetECSServiceRecommendations(ctx context.Context, params *computeoptimizer.GetECSServiceRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetECSServiceRecommendationsOutput, error)
	GetEffectiveRecommendationPreferences(ctx context.Context, params *computeoptimizer.GetEffectiveRecommendationPreferencesInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEffectiveRecommendationPreferencesOutput, error)
	GetEnrollmentStatus(ctx context.Context, params *computeoptimizer.GetEnrollmentStatusInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEnrollmentStatusOutput, error)
	GetEnrollmentStatusesForOrganization(ctx context.Context, params *computeoptimizer.GetEnrollmentStatusesForOrganizationInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetEnrollmentStatusesForOrganizationOutput, error)
	GetLambdaFunctionRecommendations(ctx context.Context, params *computeoptimizer.GetLambdaFunctionRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetLambdaFunctionRecommendationsOutput, error)
	GetLicenseRecommendations(ctx context.Context, params *computeoptimizer.GetLicenseRecommendationsInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetLicenseRecommendationsOutput, error)
	GetRecommendationPreferences(ctx context.Context, params *computeoptimizer.GetRecommendationPreferencesInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetRecommendationPreferencesOutput, error)
	GetRecommendationSummaries(ctx context.Context, params *computeoptimizer.GetRecommendationSummariesInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.GetRecommendationSummariesOutput, error)
	PutRecommendationPreferences(ctx context.Context, params *computeoptimizer.PutRecommendationPreferencesInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.PutRecommendationPreferencesOutput, error)
	UpdateEnrollmentStatus(ctx context.Context, params *computeoptimizer.UpdateEnrollmentStatusInput, optFns ...func(*computeoptimizer.Options)) (*computeoptimizer.UpdateEnrollmentStatusOutput, error)
}
