// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ec2instanceconnect"
)

// Ec2instanceconnectClient ...
type Ec2instanceconnectClient interface {
	Options() ec2instanceconnect.Options
	SendSSHPublicKey(ctx context.Context, params *ec2instanceconnect.SendSSHPublicKeyInput, optFns ...func(*ec2instanceconnect.Options)) (*ec2instanceconnect.SendSSHPublicKeyOutput, error)
	SendSerialConsoleSSHPublicKey(ctx context.Context, params *ec2instanceconnect.SendSerialConsoleSSHPublicKeyInput, optFns ...func(*ec2instanceconnect.Options)) (*ec2instanceconnect.SendSerialConsoleSSHPublicKeyOutput, error)
}
