// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/efs"
)

// EfsClient ...
type EfsClient interface {
	Options() efs.Options
	CreateAccessPoint(ctx context.Context, params *efs.CreateAccessPointInput, optFns ...func(*efs.Options)) (*efs.CreateAccessPointOutput, error)
	CreateFileSystem(ctx context.Context, params *efs.CreateFileSystemInput, optFns ...func(*efs.Options)) (*efs.CreateFileSystemOutput, error)
	CreateMountTarget(ctx context.Context, params *efs.CreateMountTargetInput, optFns ...func(*efs.Options)) (*efs.CreateMountTargetOutput, error)
	CreateReplicationConfiguration(ctx context.Context, params *efs.CreateReplicationConfigurationInput, optFns ...func(*efs.Options)) (*efs.CreateReplicationConfigurationOutput, error)
	CreateTags(ctx context.Context, params *efs.CreateTagsInput, optFns ...func(*efs.Options)) (*efs.CreateTagsOutput, error)
	DeleteAccessPoint(ctx context.Context, params *efs.DeleteAccessPointInput, optFns ...func(*efs.Options)) (*efs.DeleteAccessPointOutput, error)
	DeleteFileSystem(ctx context.Context, params *efs.DeleteFileSystemInput, optFns ...func(*efs.Options)) (*efs.DeleteFileSystemOutput, error)
	DeleteFileSystemPolicy(ctx context.Context, params *efs.DeleteFileSystemPolicyInput, optFns ...func(*efs.Options)) (*efs.DeleteFileSystemPolicyOutput, error)
	DeleteMountTarget(ctx context.Context, params *efs.DeleteMountTargetInput, optFns ...func(*efs.Options)) (*efs.DeleteMountTargetOutput, error)
	DeleteReplicationConfiguration(ctx context.Context, params *efs.DeleteReplicationConfigurationInput, optFns ...func(*efs.Options)) (*efs.DeleteReplicationConfigurationOutput, error)
	DeleteTags(ctx context.Context, params *efs.DeleteTagsInput, optFns ...func(*efs.Options)) (*efs.DeleteTagsOutput, error)
	DescribeAccessPoints(ctx context.Context, params *efs.DescribeAccessPointsInput, optFns ...func(*efs.Options)) (*efs.DescribeAccessPointsOutput, error)
	DescribeAccountPreferences(ctx context.Context, params *efs.DescribeAccountPreferencesInput, optFns ...func(*efs.Options)) (*efs.DescribeAccountPreferencesOutput, error)
	DescribeBackupPolicy(ctx context.Context, params *efs.DescribeBackupPolicyInput, optFns ...func(*efs.Options)) (*efs.DescribeBackupPolicyOutput, error)
	DescribeFileSystemPolicy(ctx context.Context, params *efs.DescribeFileSystemPolicyInput, optFns ...func(*efs.Options)) (*efs.DescribeFileSystemPolicyOutput, error)
	DescribeFileSystems(ctx context.Context, params *efs.DescribeFileSystemsInput, optFns ...func(*efs.Options)) (*efs.DescribeFileSystemsOutput, error)
	DescribeLifecycleConfiguration(ctx context.Context, params *efs.DescribeLifecycleConfigurationInput, optFns ...func(*efs.Options)) (*efs.DescribeLifecycleConfigurationOutput, error)
	DescribeMountTargetSecurityGroups(ctx context.Context, params *efs.DescribeMountTargetSecurityGroupsInput, optFns ...func(*efs.Options)) (*efs.DescribeMountTargetSecurityGroupsOutput, error)
	DescribeMountTargets(ctx context.Context, params *efs.DescribeMountTargetsInput, optFns ...func(*efs.Options)) (*efs.DescribeMountTargetsOutput, error)
	DescribeReplicationConfigurations(ctx context.Context, params *efs.DescribeReplicationConfigurationsInput, optFns ...func(*efs.Options)) (*efs.DescribeReplicationConfigurationsOutput, error)
	DescribeTags(ctx context.Context, params *efs.DescribeTagsInput, optFns ...func(*efs.Options)) (*efs.DescribeTagsOutput, error)
	ListTagsForResource(ctx context.Context, params *efs.ListTagsForResourceInput, optFns ...func(*efs.Options)) (*efs.ListTagsForResourceOutput, error)
	ModifyMountTargetSecurityGroups(ctx context.Context, params *efs.ModifyMountTargetSecurityGroupsInput, optFns ...func(*efs.Options)) (*efs.ModifyMountTargetSecurityGroupsOutput, error)
	PutAccountPreferences(ctx context.Context, params *efs.PutAccountPreferencesInput, optFns ...func(*efs.Options)) (*efs.PutAccountPreferencesOutput, error)
	PutBackupPolicy(ctx context.Context, params *efs.PutBackupPolicyInput, optFns ...func(*efs.Options)) (*efs.PutBackupPolicyOutput, error)
	PutFileSystemPolicy(ctx context.Context, params *efs.PutFileSystemPolicyInput, optFns ...func(*efs.Options)) (*efs.PutFileSystemPolicyOutput, error)
	PutLifecycleConfiguration(ctx context.Context, params *efs.PutLifecycleConfigurationInput, optFns ...func(*efs.Options)) (*efs.PutLifecycleConfigurationOutput, error)
	TagResource(ctx context.Context, params *efs.TagResourceInput, optFns ...func(*efs.Options)) (*efs.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *efs.UntagResourceInput, optFns ...func(*efs.Options)) (*efs.UntagResourceOutput, error)
	UpdateFileSystem(ctx context.Context, params *efs.UpdateFileSystemInput, optFns ...func(*efs.Options)) (*efs.UpdateFileSystemOutput, error)
	UpdateFileSystemProtection(ctx context.Context, params *efs.UpdateFileSystemProtectionInput, optFns ...func(*efs.Options)) (*efs.UpdateFileSystemProtectionOutput, error)
}
