// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/freetier"
)

// FreetierClient ...
type FreetierClient interface {
	Options() freetier.Options
	GetFreeTierUsage(ctx context.Context, params *freetier.GetFreeTierUsageInput, optFns ...func(*freetier.Options)) (*freetier.GetFreeTierUsageOutput, error)
}
