// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/grafana"
)

// GrafanaClient ...
type GrafanaClient interface {
	Options() grafana.Options
	AssociateLicense(ctx context.Context, params *grafana.AssociateLicenseInput, optFns ...func(*grafana.Options)) (*grafana.AssociateLicenseOutput, error)
	CreateWorkspace(ctx context.Context, params *grafana.CreateWorkspaceInput, optFns ...func(*grafana.Options)) (*grafana.CreateWorkspaceOutput, error)
	CreateWorkspaceApiKey(ctx context.Context, params *grafana.CreateWorkspaceApiKeyInput, optFns ...func(*grafana.Options)) (*grafana.CreateWorkspaceApiKeyOutput, error)
	DeleteWorkspace(ctx context.Context, params *grafana.DeleteWorkspaceInput, optFns ...func(*grafana.Options)) (*grafana.DeleteWorkspaceOutput, error)
	DeleteWorkspaceApiKey(ctx context.Context, params *grafana.DeleteWorkspaceApiKeyInput, optFns ...func(*grafana.Options)) (*grafana.DeleteWorkspaceApiKeyOutput, error)
	DescribeWorkspace(ctx context.Context, params *grafana.DescribeWorkspaceInput, optFns ...func(*grafana.Options)) (*grafana.DescribeWorkspaceOutput, error)
	DescribeWorkspaceAuthentication(ctx context.Context, params *grafana.DescribeWorkspaceAuthenticationInput, optFns ...func(*grafana.Options)) (*grafana.DescribeWorkspaceAuthenticationOutput, error)
	DescribeWorkspaceConfiguration(ctx context.Context, params *grafana.DescribeWorkspaceConfigurationInput, optFns ...func(*grafana.Options)) (*grafana.DescribeWorkspaceConfigurationOutput, error)
	DisassociateLicense(ctx context.Context, params *grafana.DisassociateLicenseInput, optFns ...func(*grafana.Options)) (*grafana.DisassociateLicenseOutput, error)
	ListPermissions(ctx context.Context, params *grafana.ListPermissionsInput, optFns ...func(*grafana.Options)) (*grafana.ListPermissionsOutput, error)
	ListTagsForResource(ctx context.Context, params *grafana.ListTagsForResourceInput, optFns ...func(*grafana.Options)) (*grafana.ListTagsForResourceOutput, error)
	ListVersions(ctx context.Context, params *grafana.ListVersionsInput, optFns ...func(*grafana.Options)) (*grafana.ListVersionsOutput, error)
	ListWorkspaces(ctx context.Context, params *grafana.ListWorkspacesInput, optFns ...func(*grafana.Options)) (*grafana.ListWorkspacesOutput, error)
	TagResource(ctx context.Context, params *grafana.TagResourceInput, optFns ...func(*grafana.Options)) (*grafana.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *grafana.UntagResourceInput, optFns ...func(*grafana.Options)) (*grafana.UntagResourceOutput, error)
	UpdatePermissions(ctx context.Context, params *grafana.UpdatePermissionsInput, optFns ...func(*grafana.Options)) (*grafana.UpdatePermissionsOutput, error)
	UpdateWorkspace(ctx context.Context, params *grafana.UpdateWorkspaceInput, optFns ...func(*grafana.Options)) (*grafana.UpdateWorkspaceOutput, error)
	UpdateWorkspaceAuthentication(ctx context.Context, params *grafana.UpdateWorkspaceAuthenticationInput, optFns ...func(*grafana.Options)) (*grafana.UpdateWorkspaceAuthenticationOutput, error)
	UpdateWorkspaceConfiguration(ctx context.Context, params *grafana.UpdateWorkspaceConfigurationInput, optFns ...func(*grafana.Options)) (*grafana.UpdateWorkspaceConfigurationOutput, error)
}
