// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/iottwinmaker"
)

// IottwinmakerClient ...
type IottwinmakerClient interface {
	Options() iottwinmaker.Options
	BatchPutPropertyValues(ctx context.Context, params *iottwinmaker.BatchPutPropertyValuesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.BatchPutPropertyValuesOutput, error)
	CancelMetadataTransferJob(ctx context.Context, params *iottwinmaker.CancelMetadataTransferJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CancelMetadataTransferJobOutput, error)
	CreateComponentType(ctx context.Context, params *iottwinmaker.CreateComponentTypeInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateComponentTypeOutput, error)
	CreateEntity(ctx context.Context, params *iottwinmaker.CreateEntityInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateEntityOutput, error)
	CreateMetadataTransferJob(ctx context.Context, params *iottwinmaker.CreateMetadataTransferJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateMetadataTransferJobOutput, error)
	CreateScene(ctx context.Context, params *iottwinmaker.CreateSceneInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateSceneOutput, error)
	CreateSyncJob(ctx context.Context, params *iottwinmaker.CreateSyncJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateSyncJobOutput, error)
	CreateWorkspace(ctx context.Context, params *iottwinmaker.CreateWorkspaceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.CreateWorkspaceOutput, error)
	DeleteComponentType(ctx context.Context, params *iottwinmaker.DeleteComponentTypeInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.DeleteComponentTypeOutput, error)
	DeleteEntity(ctx context.Context, params *iottwinmaker.DeleteEntityInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.DeleteEntityOutput, error)
	DeleteScene(ctx context.Context, params *iottwinmaker.DeleteSceneInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.DeleteSceneOutput, error)
	DeleteSyncJob(ctx context.Context, params *iottwinmaker.DeleteSyncJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.DeleteSyncJobOutput, error)
	DeleteWorkspace(ctx context.Context, params *iottwinmaker.DeleteWorkspaceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.DeleteWorkspaceOutput, error)
	ExecuteQuery(ctx context.Context, params *iottwinmaker.ExecuteQueryInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ExecuteQueryOutput, error)
	GetComponentType(ctx context.Context, params *iottwinmaker.GetComponentTypeInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetComponentTypeOutput, error)
	GetEntity(ctx context.Context, params *iottwinmaker.GetEntityInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetEntityOutput, error)
	GetMetadataTransferJob(ctx context.Context, params *iottwinmaker.GetMetadataTransferJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetMetadataTransferJobOutput, error)
	GetPricingPlan(ctx context.Context, params *iottwinmaker.GetPricingPlanInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetPricingPlanOutput, error)
	GetPropertyValue(ctx context.Context, params *iottwinmaker.GetPropertyValueInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetPropertyValueOutput, error)
	GetPropertyValueHistory(ctx context.Context, params *iottwinmaker.GetPropertyValueHistoryInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetPropertyValueHistoryOutput, error)
	GetScene(ctx context.Context, params *iottwinmaker.GetSceneInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetSceneOutput, error)
	GetSyncJob(ctx context.Context, params *iottwinmaker.GetSyncJobInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetSyncJobOutput, error)
	GetWorkspace(ctx context.Context, params *iottwinmaker.GetWorkspaceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.GetWorkspaceOutput, error)
	ListComponentTypes(ctx context.Context, params *iottwinmaker.ListComponentTypesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListComponentTypesOutput, error)
	ListComponents(ctx context.Context, params *iottwinmaker.ListComponentsInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListComponentsOutput, error)
	ListEntities(ctx context.Context, params *iottwinmaker.ListEntitiesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListEntitiesOutput, error)
	ListMetadataTransferJobs(ctx context.Context, params *iottwinmaker.ListMetadataTransferJobsInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListMetadataTransferJobsOutput, error)
	ListProperties(ctx context.Context, params *iottwinmaker.ListPropertiesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListPropertiesOutput, error)
	ListScenes(ctx context.Context, params *iottwinmaker.ListScenesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListScenesOutput, error)
	ListSyncJobs(ctx context.Context, params *iottwinmaker.ListSyncJobsInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListSyncJobsOutput, error)
	ListSyncResources(ctx context.Context, params *iottwinmaker.ListSyncResourcesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListSyncResourcesOutput, error)
	ListTagsForResource(ctx context.Context, params *iottwinmaker.ListTagsForResourceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListTagsForResourceOutput, error)
	ListWorkspaces(ctx context.Context, params *iottwinmaker.ListWorkspacesInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.ListWorkspacesOutput, error)
	TagResource(ctx context.Context, params *iottwinmaker.TagResourceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *iottwinmaker.UntagResourceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UntagResourceOutput, error)
	UpdateComponentType(ctx context.Context, params *iottwinmaker.UpdateComponentTypeInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UpdateComponentTypeOutput, error)
	UpdateEntity(ctx context.Context, params *iottwinmaker.UpdateEntityInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UpdateEntityOutput, error)
	UpdatePricingPlan(ctx context.Context, params *iottwinmaker.UpdatePricingPlanInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UpdatePricingPlanOutput, error)
	UpdateScene(ctx context.Context, params *iottwinmaker.UpdateSceneInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UpdateSceneOutput, error)
	UpdateWorkspace(ctx context.Context, params *iottwinmaker.UpdateWorkspaceInput, optFns ...func(*iottwinmaker.Options)) (*iottwinmaker.UpdateWorkspaceOutput, error)
}
