// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kendraranking"
)

// KendrarankingClient ...
type KendrarankingClient interface {
	Options() kendraranking.Options
	CreateRescoreExecutionPlan(ctx context.Context, params *kendraranking.CreateRescoreExecutionPlanInput, optFns ...func(*kendraranking.Options)) (*kendraranking.CreateRescoreExecutionPlanOutput, error)
	DeleteRescoreExecutionPlan(ctx context.Context, params *kendraranking.DeleteRescoreExecutionPlanInput, optFns ...func(*kendraranking.Options)) (*kendraranking.DeleteRescoreExecutionPlanOutput, error)
	DescribeRescoreExecutionPlan(ctx context.Context, params *kendraranking.DescribeRescoreExecutionPlanInput, optFns ...func(*kendraranking.Options)) (*kendraranking.DescribeRescoreExecutionPlanOutput, error)
	ListRescoreExecutionPlans(ctx context.Context, params *kendraranking.ListRescoreExecutionPlansInput, optFns ...func(*kendraranking.Options)) (*kendraranking.ListRescoreExecutionPlansOutput, error)
	ListTagsForResource(ctx context.Context, params *kendraranking.ListTagsForResourceInput, optFns ...func(*kendraranking.Options)) (*kendraranking.ListTagsForResourceOutput, error)
	Rescore(ctx context.Context, params *kendraranking.RescoreInput, optFns ...func(*kendraranking.Options)) (*kendraranking.RescoreOutput, error)
	TagResource(ctx context.Context, params *kendraranking.TagResourceInput, optFns ...func(*kendraranking.Options)) (*kendraranking.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *kendraranking.UntagResourceInput, optFns ...func(*kendraranking.Options)) (*kendraranking.UntagResourceOutput, error)
	UpdateRescoreExecutionPlan(ctx context.Context, params *kendraranking.UpdateRescoreExecutionPlanInput, optFns ...func(*kendraranking.Options)) (*kendraranking.UpdateRescoreExecutionPlanOutput, error)
}
