// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kinesisanalyticsv2"
)

// Kinesisanalyticsv2Client ...
type Kinesisanalyticsv2Client interface {
	Options() kinesisanalyticsv2.Options
	AddApplicationCloudWatchLoggingOption(ctx context.Context, params *kinesisanalyticsv2.AddApplicationCloudWatchLoggingOptionInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationCloudWatchLoggingOptionOutput, error)
	AddApplicationInput(ctx context.Context, params *kinesisanalyticsv2.AddApplicationInputInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationInputOutput, error)
	AddApplicationInputProcessingConfiguration(ctx context.Context, params *kinesisanalyticsv2.AddApplicationInputProcessingConfigurationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationInputProcessingConfigurationOutput, error)
	AddApplicationOutput(ctx context.Context, params *kinesisanalyticsv2.AddApplicationOutputInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationOutputOutput, error)
	AddApplicationReferenceDataSource(ctx context.Context, params *kinesisanalyticsv2.AddApplicationReferenceDataSourceInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationReferenceDataSourceOutput, error)
	AddApplicationVpcConfiguration(ctx context.Context, params *kinesisanalyticsv2.AddApplicationVpcConfigurationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.AddApplicationVpcConfigurationOutput, error)
	CreateApplication(ctx context.Context, params *kinesisanalyticsv2.CreateApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.CreateApplicationOutput, error)
	CreateApplicationPresignedUrl(ctx context.Context, params *kinesisanalyticsv2.CreateApplicationPresignedUrlInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.CreateApplicationPresignedUrlOutput, error)
	CreateApplicationSnapshot(ctx context.Context, params *kinesisanalyticsv2.CreateApplicationSnapshotInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.CreateApplicationSnapshotOutput, error)
	DeleteApplication(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationOutput, error)
	DeleteApplicationCloudWatchLoggingOption(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationCloudWatchLoggingOptionInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationCloudWatchLoggingOptionOutput, error)
	DeleteApplicationInputProcessingConfiguration(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationInputProcessingConfigurationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationInputProcessingConfigurationOutput, error)
	DeleteApplicationOutput(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationOutputInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationOutputOutput, error)
	DeleteApplicationReferenceDataSource(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationReferenceDataSourceInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationReferenceDataSourceOutput, error)
	DeleteApplicationSnapshot(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationSnapshotInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationSnapshotOutput, error)
	DeleteApplicationVpcConfiguration(ctx context.Context, params *kinesisanalyticsv2.DeleteApplicationVpcConfigurationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DeleteApplicationVpcConfigurationOutput, error)
	DescribeApplication(ctx context.Context, params *kinesisanalyticsv2.DescribeApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DescribeApplicationOutput, error)
	DescribeApplicationSnapshot(ctx context.Context, params *kinesisanalyticsv2.DescribeApplicationSnapshotInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DescribeApplicationSnapshotOutput, error)
	DescribeApplicationVersion(ctx context.Context, params *kinesisanalyticsv2.DescribeApplicationVersionInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DescribeApplicationVersionOutput, error)
	DiscoverInputSchema(ctx context.Context, params *kinesisanalyticsv2.DiscoverInputSchemaInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.DiscoverInputSchemaOutput, error)
	ListApplicationSnapshots(ctx context.Context, params *kinesisanalyticsv2.ListApplicationSnapshotsInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.ListApplicationSnapshotsOutput, error)
	ListApplicationVersions(ctx context.Context, params *kinesisanalyticsv2.ListApplicationVersionsInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.ListApplicationVersionsOutput, error)
	ListApplications(ctx context.Context, params *kinesisanalyticsv2.ListApplicationsInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.ListApplicationsOutput, error)
	ListTagsForResource(ctx context.Context, params *kinesisanalyticsv2.ListTagsForResourceInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.ListTagsForResourceOutput, error)
	RollbackApplication(ctx context.Context, params *kinesisanalyticsv2.RollbackApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.RollbackApplicationOutput, error)
	StartApplication(ctx context.Context, params *kinesisanalyticsv2.StartApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.StartApplicationOutput, error)
	StopApplication(ctx context.Context, params *kinesisanalyticsv2.StopApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.StopApplicationOutput, error)
	TagResource(ctx context.Context, params *kinesisanalyticsv2.TagResourceInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *kinesisanalyticsv2.UntagResourceInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.UntagResourceOutput, error)
	UpdateApplication(ctx context.Context, params *kinesisanalyticsv2.UpdateApplicationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.UpdateApplicationOutput, error)
	UpdateApplicationMaintenanceConfiguration(ctx context.Context, params *kinesisanalyticsv2.UpdateApplicationMaintenanceConfigurationInput, optFns ...func(*kinesisanalyticsv2.Options)) (*kinesisanalyticsv2.UpdateApplicationMaintenanceConfigurationOutput, error)
}
