// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/lookoutmetrics"
)

// LookoutmetricsClient ...
type LookoutmetricsClient interface {
	Options() lookoutmetrics.Options
	ActivateAnomalyDetector(ctx context.Context, params *lookoutmetrics.ActivateAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ActivateAnomalyDetectorOutput, error)
	BackTestAnomalyDetector(ctx context.Context, params *lookoutmetrics.BackTestAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.BackTestAnomalyDetectorOutput, error)
	CreateAlert(ctx context.Context, params *lookoutmetrics.CreateAlertInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.CreateAlertOutput, error)
	CreateAnomalyDetector(ctx context.Context, params *lookoutmetrics.CreateAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.CreateAnomalyDetectorOutput, error)
	CreateMetricSet(ctx context.Context, params *lookoutmetrics.CreateMetricSetInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.CreateMetricSetOutput, error)
	DeactivateAnomalyDetector(ctx context.Context, params *lookoutmetrics.DeactivateAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DeactivateAnomalyDetectorOutput, error)
	DeleteAlert(ctx context.Context, params *lookoutmetrics.DeleteAlertInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DeleteAlertOutput, error)
	DeleteAnomalyDetector(ctx context.Context, params *lookoutmetrics.DeleteAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DeleteAnomalyDetectorOutput, error)
	DescribeAlert(ctx context.Context, params *lookoutmetrics.DescribeAlertInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DescribeAlertOutput, error)
	DescribeAnomalyDetectionExecutions(ctx context.Context, params *lookoutmetrics.DescribeAnomalyDetectionExecutionsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DescribeAnomalyDetectionExecutionsOutput, error)
	DescribeAnomalyDetector(ctx context.Context, params *lookoutmetrics.DescribeAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DescribeAnomalyDetectorOutput, error)
	DescribeMetricSet(ctx context.Context, params *lookoutmetrics.DescribeMetricSetInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DescribeMetricSetOutput, error)
	DetectMetricSetConfig(ctx context.Context, params *lookoutmetrics.DetectMetricSetConfigInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.DetectMetricSetConfigOutput, error)
	GetAnomalyGroup(ctx context.Context, params *lookoutmetrics.GetAnomalyGroupInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.GetAnomalyGroupOutput, error)
	GetDataQualityMetrics(ctx context.Context, params *lookoutmetrics.GetDataQualityMetricsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.GetDataQualityMetricsOutput, error)
	GetFeedback(ctx context.Context, params *lookoutmetrics.GetFeedbackInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.GetFeedbackOutput, error)
	GetSampleData(ctx context.Context, params *lookoutmetrics.GetSampleDataInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.GetSampleDataOutput, error)
	ListAlerts(ctx context.Context, params *lookoutmetrics.ListAlertsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListAlertsOutput, error)
	ListAnomalyDetectors(ctx context.Context, params *lookoutmetrics.ListAnomalyDetectorsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListAnomalyDetectorsOutput, error)
	ListAnomalyGroupRelatedMetrics(ctx context.Context, params *lookoutmetrics.ListAnomalyGroupRelatedMetricsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListAnomalyGroupRelatedMetricsOutput, error)
	ListAnomalyGroupSummaries(ctx context.Context, params *lookoutmetrics.ListAnomalyGroupSummariesInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListAnomalyGroupSummariesOutput, error)
	ListAnomalyGroupTimeSeries(ctx context.Context, params *lookoutmetrics.ListAnomalyGroupTimeSeriesInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListAnomalyGroupTimeSeriesOutput, error)
	ListMetricSets(ctx context.Context, params *lookoutmetrics.ListMetricSetsInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListMetricSetsOutput, error)
	ListTagsForResource(ctx context.Context, params *lookoutmetrics.ListTagsForResourceInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.ListTagsForResourceOutput, error)
	PutFeedback(ctx context.Context, params *lookoutmetrics.PutFeedbackInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.PutFeedbackOutput, error)
	TagResource(ctx context.Context, params *lookoutmetrics.TagResourceInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *lookoutmetrics.UntagResourceInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.UntagResourceOutput, error)
	UpdateAlert(ctx context.Context, params *lookoutmetrics.UpdateAlertInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.UpdateAlertOutput, error)
	UpdateAnomalyDetector(ctx context.Context, params *lookoutmetrics.UpdateAnomalyDetectorInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.UpdateAnomalyDetectorOutput, error)
	UpdateMetricSet(ctx context.Context, params *lookoutmetrics.UpdateMetricSetInput, optFns ...func(*lookoutmetrics.Options)) (*lookoutmetrics.UpdateMetricSetOutput, error)
}
