// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/lookoutvision"
)

// LookoutvisionClient ...
type LookoutvisionClient interface {
	Options() lookoutvision.Options
	CreateDataset(ctx context.Context, params *lookoutvision.CreateDatasetInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.CreateDatasetOutput, error)
	CreateModel(ctx context.Context, params *lookoutvision.CreateModelInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.CreateModelOutput, error)
	CreateProject(ctx context.Context, params *lookoutvision.CreateProjectInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.CreateProjectOutput, error)
	DeleteDataset(ctx context.Context, params *lookoutvision.DeleteDatasetInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DeleteDatasetOutput, error)
	DeleteModel(ctx context.Context, params *lookoutvision.DeleteModelInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DeleteModelOutput, error)
	DeleteProject(ctx context.Context, params *lookoutvision.DeleteProjectInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DeleteProjectOutput, error)
	DescribeDataset(ctx context.Context, params *lookoutvision.DescribeDatasetInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DescribeDatasetOutput, error)
	DescribeModel(ctx context.Context, params *lookoutvision.DescribeModelInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DescribeModelOutput, error)
	DescribeModelPackagingJob(ctx context.Context, params *lookoutvision.DescribeModelPackagingJobInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DescribeModelPackagingJobOutput, error)
	DescribeProject(ctx context.Context, params *lookoutvision.DescribeProjectInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DescribeProjectOutput, error)
	DetectAnomalies(ctx context.Context, params *lookoutvision.DetectAnomaliesInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.DetectAnomaliesOutput, error)
	ListDatasetEntries(ctx context.Context, params *lookoutvision.ListDatasetEntriesInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.ListDatasetEntriesOutput, error)
	ListModelPackagingJobs(ctx context.Context, params *lookoutvision.ListModelPackagingJobsInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.ListModelPackagingJobsOutput, error)
	ListModels(ctx context.Context, params *lookoutvision.ListModelsInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.ListModelsOutput, error)
	ListProjects(ctx context.Context, params *lookoutvision.ListProjectsInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.ListProjectsOutput, error)
	ListTagsForResource(ctx context.Context, params *lookoutvision.ListTagsForResourceInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.ListTagsForResourceOutput, error)
	StartModel(ctx context.Context, params *lookoutvision.StartModelInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.StartModelOutput, error)
	StartModelPackagingJob(ctx context.Context, params *lookoutvision.StartModelPackagingJobInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.StartModelPackagingJobOutput, error)
	StopModel(ctx context.Context, params *lookoutvision.StopModelInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.StopModelOutput, error)
	TagResource(ctx context.Context, params *lookoutvision.TagResourceInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *lookoutvision.UntagResourceInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.UntagResourceOutput, error)
	UpdateDatasetEntries(ctx context.Context, params *lookoutvision.UpdateDatasetEntriesInput, optFns ...func(*lookoutvision.Options)) (*lookoutvision.UpdateDatasetEntriesOutput, error)
}
