// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/marketplacedeployment"
)

// MarketplacedeploymentClient ...
type MarketplacedeploymentClient interface {
	Options() marketplacedeployment.Options
	ListTagsForResource(ctx context.Context, params *marketplacedeployment.ListTagsForResourceInput, optFns ...func(*marketplacedeployment.Options)) (*marketplacedeployment.ListTagsForResourceOutput, error)
	PutDeploymentParameter(ctx context.Context, params *marketplacedeployment.PutDeploymentParameterInput, optFns ...func(*marketplacedeployment.Options)) (*marketplacedeployment.PutDeploymentParameterOutput, error)
	TagResource(ctx context.Context, params *marketplacedeployment.TagResourceInput, optFns ...func(*marketplacedeployment.Options)) (*marketplacedeployment.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *marketplacedeployment.UntagResourceInput, optFns ...func(*marketplacedeployment.Options)) (*marketplacedeployment.UntagResourceOutput, error)
}
