// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/mediaconnect"
)

// MediaconnectClient ...
type MediaconnectClient interface {
	Options() mediaconnect.Options
	AddBridgeOutputs(ctx context.Context, params *mediaconnect.AddBridgeOutputsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddBridgeOutputsOutput, error)
	AddBridgeSources(ctx context.Context, params *mediaconnect.AddBridgeSourcesInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddBridgeSourcesOutput, error)
	AddFlowMediaStreams(ctx context.Context, params *mediaconnect.AddFlowMediaStreamsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddFlowMediaStreamsOutput, error)
	AddFlowOutputs(ctx context.Context, params *mediaconnect.AddFlowOutputsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddFlowOutputsOutput, error)
	AddFlowSources(ctx context.Context, params *mediaconnect.AddFlowSourcesInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddFlowSourcesOutput, error)
	AddFlowVpcInterfaces(ctx context.Context, params *mediaconnect.AddFlowVpcInterfacesInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.AddFlowVpcInterfacesOutput, error)
	CreateBridge(ctx context.Context, params *mediaconnect.CreateBridgeInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.CreateBridgeOutput, error)
	CreateFlow(ctx context.Context, params *mediaconnect.CreateFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.CreateFlowOutput, error)
	CreateGateway(ctx context.Context, params *mediaconnect.CreateGatewayInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.CreateGatewayOutput, error)
	DeleteBridge(ctx context.Context, params *mediaconnect.DeleteBridgeInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DeleteBridgeOutput, error)
	DeleteFlow(ctx context.Context, params *mediaconnect.DeleteFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DeleteFlowOutput, error)
	DeleteGateway(ctx context.Context, params *mediaconnect.DeleteGatewayInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DeleteGatewayOutput, error)
	DeregisterGatewayInstance(ctx context.Context, params *mediaconnect.DeregisterGatewayInstanceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DeregisterGatewayInstanceOutput, error)
	DescribeBridge(ctx context.Context, params *mediaconnect.DescribeBridgeInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeBridgeOutput, error)
	DescribeFlow(ctx context.Context, params *mediaconnect.DescribeFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeFlowOutput, error)
	DescribeFlowSourceMetadata(ctx context.Context, params *mediaconnect.DescribeFlowSourceMetadataInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeFlowSourceMetadataOutput, error)
	DescribeGateway(ctx context.Context, params *mediaconnect.DescribeGatewayInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeGatewayOutput, error)
	DescribeGatewayInstance(ctx context.Context, params *mediaconnect.DescribeGatewayInstanceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeGatewayInstanceOutput, error)
	DescribeOffering(ctx context.Context, params *mediaconnect.DescribeOfferingInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeOfferingOutput, error)
	DescribeReservation(ctx context.Context, params *mediaconnect.DescribeReservationInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.DescribeReservationOutput, error)
	GrantFlowEntitlements(ctx context.Context, params *mediaconnect.GrantFlowEntitlementsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.GrantFlowEntitlementsOutput, error)
	ListBridges(ctx context.Context, params *mediaconnect.ListBridgesInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListBridgesOutput, error)
	ListEntitlements(ctx context.Context, params *mediaconnect.ListEntitlementsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListEntitlementsOutput, error)
	ListFlows(ctx context.Context, params *mediaconnect.ListFlowsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListFlowsOutput, error)
	ListGatewayInstances(ctx context.Context, params *mediaconnect.ListGatewayInstancesInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListGatewayInstancesOutput, error)
	ListGateways(ctx context.Context, params *mediaconnect.ListGatewaysInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListGatewaysOutput, error)
	ListOfferings(ctx context.Context, params *mediaconnect.ListOfferingsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListOfferingsOutput, error)
	ListReservations(ctx context.Context, params *mediaconnect.ListReservationsInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListReservationsOutput, error)
	ListTagsForResource(ctx context.Context, params *mediaconnect.ListTagsForResourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.ListTagsForResourceOutput, error)
	PurchaseOffering(ctx context.Context, params *mediaconnect.PurchaseOfferingInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.PurchaseOfferingOutput, error)
	RemoveBridgeOutput(ctx context.Context, params *mediaconnect.RemoveBridgeOutputInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveBridgeOutputOutput, error)
	RemoveBridgeSource(ctx context.Context, params *mediaconnect.RemoveBridgeSourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveBridgeSourceOutput, error)
	RemoveFlowMediaStream(ctx context.Context, params *mediaconnect.RemoveFlowMediaStreamInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveFlowMediaStreamOutput, error)
	RemoveFlowOutput(ctx context.Context, params *mediaconnect.RemoveFlowOutputInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveFlowOutputOutput, error)
	RemoveFlowSource(ctx context.Context, params *mediaconnect.RemoveFlowSourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveFlowSourceOutput, error)
	RemoveFlowVpcInterface(ctx context.Context, params *mediaconnect.RemoveFlowVpcInterfaceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RemoveFlowVpcInterfaceOutput, error)
	RevokeFlowEntitlement(ctx context.Context, params *mediaconnect.RevokeFlowEntitlementInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.RevokeFlowEntitlementOutput, error)
	StartFlow(ctx context.Context, params *mediaconnect.StartFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.StartFlowOutput, error)
	StopFlow(ctx context.Context, params *mediaconnect.StopFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.StopFlowOutput, error)
	TagResource(ctx context.Context, params *mediaconnect.TagResourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *mediaconnect.UntagResourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UntagResourceOutput, error)
	UpdateBridge(ctx context.Context, params *mediaconnect.UpdateBridgeInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateBridgeOutput, error)
	UpdateBridgeOutput(ctx context.Context, params *mediaconnect.UpdateBridgeOutputInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateBridgeOutputOutput, error)
	UpdateBridgeSource(ctx context.Context, params *mediaconnect.UpdateBridgeSourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateBridgeSourceOutput, error)
	UpdateBridgeState(ctx context.Context, params *mediaconnect.UpdateBridgeStateInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateBridgeStateOutput, error)
	UpdateFlow(ctx context.Context, params *mediaconnect.UpdateFlowInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateFlowOutput, error)
	UpdateFlowEntitlement(ctx context.Context, params *mediaconnect.UpdateFlowEntitlementInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateFlowEntitlementOutput, error)
	UpdateFlowMediaStream(ctx context.Context, params *mediaconnect.UpdateFlowMediaStreamInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateFlowMediaStreamOutput, error)
	UpdateFlowOutput(ctx context.Context, params *mediaconnect.UpdateFlowOutputInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateFlowOutputOutput, error)
	UpdateFlowSource(ctx context.Context, params *mediaconnect.UpdateFlowSourceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateFlowSourceOutput, error)
	UpdateGatewayInstance(ctx context.Context, params *mediaconnect.UpdateGatewayInstanceInput, optFns ...func(*mediaconnect.Options)) (*mediaconnect.UpdateGatewayInstanceOutput, error)
}
