// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/mq"
)

// MqClient ...
type MqClient interface {
	Options() mq.Options
	CreateBroker(ctx context.Context, params *mq.CreateBrokerInput, optFns ...func(*mq.Options)) (*mq.CreateBrokerOutput, error)
	CreateConfiguration(ctx context.Context, params *mq.CreateConfigurationInput, optFns ...func(*mq.Options)) (*mq.CreateConfigurationOutput, error)
	CreateTags(ctx context.Context, params *mq.CreateTagsInput, optFns ...func(*mq.Options)) (*mq.CreateTagsOutput, error)
	CreateUser(ctx context.Context, params *mq.CreateUserInput, optFns ...func(*mq.Options)) (*mq.CreateUserOutput, error)
	DeleteBroker(ctx context.Context, params *mq.DeleteBrokerInput, optFns ...func(*mq.Options)) (*mq.DeleteBrokerOutput, error)
	DeleteTags(ctx context.Context, params *mq.DeleteTagsInput, optFns ...func(*mq.Options)) (*mq.DeleteTagsOutput, error)
	DeleteUser(ctx context.Context, params *mq.DeleteUserInput, optFns ...func(*mq.Options)) (*mq.DeleteUserOutput, error)
	DescribeBroker(ctx context.Context, params *mq.DescribeBrokerInput, optFns ...func(*mq.Options)) (*mq.DescribeBrokerOutput, error)
	DescribeBrokerEngineTypes(ctx context.Context, params *mq.DescribeBrokerEngineTypesInput, optFns ...func(*mq.Options)) (*mq.DescribeBrokerEngineTypesOutput, error)
	DescribeBrokerInstanceOptions(ctx context.Context, params *mq.DescribeBrokerInstanceOptionsInput, optFns ...func(*mq.Options)) (*mq.DescribeBrokerInstanceOptionsOutput, error)
	DescribeConfiguration(ctx context.Context, params *mq.DescribeConfigurationInput, optFns ...func(*mq.Options)) (*mq.DescribeConfigurationOutput, error)
	DescribeConfigurationRevision(ctx context.Context, params *mq.DescribeConfigurationRevisionInput, optFns ...func(*mq.Options)) (*mq.DescribeConfigurationRevisionOutput, error)
	DescribeUser(ctx context.Context, params *mq.DescribeUserInput, optFns ...func(*mq.Options)) (*mq.DescribeUserOutput, error)
	ListBrokers(ctx context.Context, params *mq.ListBrokersInput, optFns ...func(*mq.Options)) (*mq.ListBrokersOutput, error)
	ListConfigurationRevisions(ctx context.Context, params *mq.ListConfigurationRevisionsInput, optFns ...func(*mq.Options)) (*mq.ListConfigurationRevisionsOutput, error)
	ListConfigurations(ctx context.Context, params *mq.ListConfigurationsInput, optFns ...func(*mq.Options)) (*mq.ListConfigurationsOutput, error)
	ListTags(ctx context.Context, params *mq.ListTagsInput, optFns ...func(*mq.Options)) (*mq.ListTagsOutput, error)
	ListUsers(ctx context.Context, params *mq.ListUsersInput, optFns ...func(*mq.Options)) (*mq.ListUsersOutput, error)
	Promote(ctx context.Context, params *mq.PromoteInput, optFns ...func(*mq.Options)) (*mq.PromoteOutput, error)
	RebootBroker(ctx context.Context, params *mq.RebootBrokerInput, optFns ...func(*mq.Options)) (*mq.RebootBrokerOutput, error)
	UpdateBroker(ctx context.Context, params *mq.UpdateBrokerInput, optFns ...func(*mq.Options)) (*mq.UpdateBrokerOutput, error)
	UpdateConfiguration(ctx context.Context, params *mq.UpdateConfigurationInput, optFns ...func(*mq.Options)) (*mq.UpdateConfigurationOutput, error)
	UpdateUser(ctx context.Context, params *mq.UpdateUserInput, optFns ...func(*mq.Options)) (*mq.UpdateUserOutput, error)
}
