// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/mturk"
)

// MturkClient ...
type MturkClient interface {
	Options() mturk.Options
	AcceptQualificationRequest(ctx context.Context, params *mturk.AcceptQualificationRequestInput, optFns ...func(*mturk.Options)) (*mturk.AcceptQualificationRequestOutput, error)
	ApproveAssignment(ctx context.Context, params *mturk.ApproveAssignmentInput, optFns ...func(*mturk.Options)) (*mturk.ApproveAssignmentOutput, error)
	AssociateQualificationWithWorker(ctx context.Context, params *mturk.AssociateQualificationWithWorkerInput, optFns ...func(*mturk.Options)) (*mturk.AssociateQualificationWithWorkerOutput, error)
	CreateAdditionalAssignmentsForHIT(ctx context.Context, params *mturk.CreateAdditionalAssignmentsForHITInput, optFns ...func(*mturk.Options)) (*mturk.CreateAdditionalAssignmentsForHITOutput, error)
	CreateHIT(ctx context.Context, params *mturk.CreateHITInput, optFns ...func(*mturk.Options)) (*mturk.CreateHITOutput, error)
	CreateHITType(ctx context.Context, params *mturk.CreateHITTypeInput, optFns ...func(*mturk.Options)) (*mturk.CreateHITTypeOutput, error)
	CreateHITWithHITType(ctx context.Context, params *mturk.CreateHITWithHITTypeInput, optFns ...func(*mturk.Options)) (*mturk.CreateHITWithHITTypeOutput, error)
	CreateQualificationType(ctx context.Context, params *mturk.CreateQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.CreateQualificationTypeOutput, error)
	CreateWorkerBlock(ctx context.Context, params *mturk.CreateWorkerBlockInput, optFns ...func(*mturk.Options)) (*mturk.CreateWorkerBlockOutput, error)
	DeleteHIT(ctx context.Context, params *mturk.DeleteHITInput, optFns ...func(*mturk.Options)) (*mturk.DeleteHITOutput, error)
	DeleteQualificationType(ctx context.Context, params *mturk.DeleteQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.DeleteQualificationTypeOutput, error)
	DeleteWorkerBlock(ctx context.Context, params *mturk.DeleteWorkerBlockInput, optFns ...func(*mturk.Options)) (*mturk.DeleteWorkerBlockOutput, error)
	DisassociateQualificationFromWorker(ctx context.Context, params *mturk.DisassociateQualificationFromWorkerInput, optFns ...func(*mturk.Options)) (*mturk.DisassociateQualificationFromWorkerOutput, error)
	GetAccountBalance(ctx context.Context, params *mturk.GetAccountBalanceInput, optFns ...func(*mturk.Options)) (*mturk.GetAccountBalanceOutput, error)
	GetAssignment(ctx context.Context, params *mturk.GetAssignmentInput, optFns ...func(*mturk.Options)) (*mturk.GetAssignmentOutput, error)
	GetFileUploadURL(ctx context.Context, params *mturk.GetFileUploadURLInput, optFns ...func(*mturk.Options)) (*mturk.GetFileUploadURLOutput, error)
	GetHIT(ctx context.Context, params *mturk.GetHITInput, optFns ...func(*mturk.Options)) (*mturk.GetHITOutput, error)
	GetQualificationScore(ctx context.Context, params *mturk.GetQualificationScoreInput, optFns ...func(*mturk.Options)) (*mturk.GetQualificationScoreOutput, error)
	GetQualificationType(ctx context.Context, params *mturk.GetQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.GetQualificationTypeOutput, error)
	ListAssignmentsForHIT(ctx context.Context, params *mturk.ListAssignmentsForHITInput, optFns ...func(*mturk.Options)) (*mturk.ListAssignmentsForHITOutput, error)
	ListBonusPayments(ctx context.Context, params *mturk.ListBonusPaymentsInput, optFns ...func(*mturk.Options)) (*mturk.ListBonusPaymentsOutput, error)
	ListHITs(ctx context.Context, params *mturk.ListHITsInput, optFns ...func(*mturk.Options)) (*mturk.ListHITsOutput, error)
	ListHITsForQualificationType(ctx context.Context, params *mturk.ListHITsForQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.ListHITsForQualificationTypeOutput, error)
	ListQualificationRequests(ctx context.Context, params *mturk.ListQualificationRequestsInput, optFns ...func(*mturk.Options)) (*mturk.ListQualificationRequestsOutput, error)
	ListQualificationTypes(ctx context.Context, params *mturk.ListQualificationTypesInput, optFns ...func(*mturk.Options)) (*mturk.ListQualificationTypesOutput, error)
	ListReviewPolicyResultsForHIT(ctx context.Context, params *mturk.ListReviewPolicyResultsForHITInput, optFns ...func(*mturk.Options)) (*mturk.ListReviewPolicyResultsForHITOutput, error)
	ListReviewableHITs(ctx context.Context, params *mturk.ListReviewableHITsInput, optFns ...func(*mturk.Options)) (*mturk.ListReviewableHITsOutput, error)
	ListWorkerBlocks(ctx context.Context, params *mturk.ListWorkerBlocksInput, optFns ...func(*mturk.Options)) (*mturk.ListWorkerBlocksOutput, error)
	ListWorkersWithQualificationType(ctx context.Context, params *mturk.ListWorkersWithQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.ListWorkersWithQualificationTypeOutput, error)
	NotifyWorkers(ctx context.Context, params *mturk.NotifyWorkersInput, optFns ...func(*mturk.Options)) (*mturk.NotifyWorkersOutput, error)
	RejectAssignment(ctx context.Context, params *mturk.RejectAssignmentInput, optFns ...func(*mturk.Options)) (*mturk.RejectAssignmentOutput, error)
	RejectQualificationRequest(ctx context.Context, params *mturk.RejectQualificationRequestInput, optFns ...func(*mturk.Options)) (*mturk.RejectQualificationRequestOutput, error)
	SendBonus(ctx context.Context, params *mturk.SendBonusInput, optFns ...func(*mturk.Options)) (*mturk.SendBonusOutput, error)
	SendTestEventNotification(ctx context.Context, params *mturk.SendTestEventNotificationInput, optFns ...func(*mturk.Options)) (*mturk.SendTestEventNotificationOutput, error)
	UpdateExpirationForHIT(ctx context.Context, params *mturk.UpdateExpirationForHITInput, optFns ...func(*mturk.Options)) (*mturk.UpdateExpirationForHITOutput, error)
	UpdateHITReviewStatus(ctx context.Context, params *mturk.UpdateHITReviewStatusInput, optFns ...func(*mturk.Options)) (*mturk.UpdateHITReviewStatusOutput, error)
	UpdateHITTypeOfHIT(ctx context.Context, params *mturk.UpdateHITTypeOfHITInput, optFns ...func(*mturk.Options)) (*mturk.UpdateHITTypeOfHITOutput, error)
	UpdateNotificationSettings(ctx context.Context, params *mturk.UpdateNotificationSettingsInput, optFns ...func(*mturk.Options)) (*mturk.UpdateNotificationSettingsOutput, error)
	UpdateQualificationType(ctx context.Context, params *mturk.UpdateQualificationTypeInput, optFns ...func(*mturk.Options)) (*mturk.UpdateQualificationTypeOutput, error)
}
