// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/neptunedata"
)

// NeptunedataClient ...
type NeptunedataClient interface {
	Options() neptunedata.Options
	CancelGremlinQuery(ctx context.Context, params *neptunedata.CancelGremlinQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelGremlinQueryOutput, error)
	CancelLoaderJob(ctx context.Context, params *neptunedata.CancelLoaderJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelLoaderJobOutput, error)
	CancelMLDataProcessingJob(ctx context.Context, params *neptunedata.CancelMLDataProcessingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelMLDataProcessingJobOutput, error)
	CancelMLModelTrainingJob(ctx context.Context, params *neptunedata.CancelMLModelTrainingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelMLModelTrainingJobOutput, error)
	CancelMLModelTransformJob(ctx context.Context, params *neptunedata.CancelMLModelTransformJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelMLModelTransformJobOutput, error)
	CancelOpenCypherQuery(ctx context.Context, params *neptunedata.CancelOpenCypherQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CancelOpenCypherQueryOutput, error)
	CreateMLEndpoint(ctx context.Context, params *neptunedata.CreateMLEndpointInput, optFns ...func(*neptunedata.Options)) (*neptunedata.CreateMLEndpointOutput, error)
	DeleteMLEndpoint(ctx context.Context, params *neptunedata.DeleteMLEndpointInput, optFns ...func(*neptunedata.Options)) (*neptunedata.DeleteMLEndpointOutput, error)
	DeletePropertygraphStatistics(ctx context.Context, params *neptunedata.DeletePropertygraphStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.DeletePropertygraphStatisticsOutput, error)
	DeleteSparqlStatistics(ctx context.Context, params *neptunedata.DeleteSparqlStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.DeleteSparqlStatisticsOutput, error)
	ExecuteFastReset(ctx context.Context, params *neptunedata.ExecuteFastResetInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteFastResetOutput, error)
	ExecuteGremlinExplainQuery(ctx context.Context, params *neptunedata.ExecuteGremlinExplainQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteGremlinExplainQueryOutput, error)
	ExecuteGremlinProfileQuery(ctx context.Context, params *neptunedata.ExecuteGremlinProfileQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteGremlinProfileQueryOutput, error)
	ExecuteGremlinQuery(ctx context.Context, params *neptunedata.ExecuteGremlinQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteGremlinQueryOutput, error)
	ExecuteOpenCypherExplainQuery(ctx context.Context, params *neptunedata.ExecuteOpenCypherExplainQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteOpenCypherExplainQueryOutput, error)
	ExecuteOpenCypherQuery(ctx context.Context, params *neptunedata.ExecuteOpenCypherQueryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ExecuteOpenCypherQueryOutput, error)
	GetEngineStatus(ctx context.Context, params *neptunedata.GetEngineStatusInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetEngineStatusOutput, error)
	GetGremlinQueryStatus(ctx context.Context, params *neptunedata.GetGremlinQueryStatusInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetGremlinQueryStatusOutput, error)
	GetLoaderJobStatus(ctx context.Context, params *neptunedata.GetLoaderJobStatusInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetLoaderJobStatusOutput, error)
	GetMLDataProcessingJob(ctx context.Context, params *neptunedata.GetMLDataProcessingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetMLDataProcessingJobOutput, error)
	GetMLEndpoint(ctx context.Context, params *neptunedata.GetMLEndpointInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetMLEndpointOutput, error)
	GetMLModelTrainingJob(ctx context.Context, params *neptunedata.GetMLModelTrainingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetMLModelTrainingJobOutput, error)
	GetMLModelTransformJob(ctx context.Context, params *neptunedata.GetMLModelTransformJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetMLModelTransformJobOutput, error)
	GetOpenCypherQueryStatus(ctx context.Context, params *neptunedata.GetOpenCypherQueryStatusInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetOpenCypherQueryStatusOutput, error)
	GetPropertygraphStatistics(ctx context.Context, params *neptunedata.GetPropertygraphStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetPropertygraphStatisticsOutput, error)
	GetPropertygraphStream(ctx context.Context, params *neptunedata.GetPropertygraphStreamInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetPropertygraphStreamOutput, error)
	GetPropertygraphSummary(ctx context.Context, params *neptunedata.GetPropertygraphSummaryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetPropertygraphSummaryOutput, error)
	GetRDFGraphSummary(ctx context.Context, params *neptunedata.GetRDFGraphSummaryInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetRDFGraphSummaryOutput, error)
	GetSparqlStatistics(ctx context.Context, params *neptunedata.GetSparqlStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetSparqlStatisticsOutput, error)
	GetSparqlStream(ctx context.Context, params *neptunedata.GetSparqlStreamInput, optFns ...func(*neptunedata.Options)) (*neptunedata.GetSparqlStreamOutput, error)
	ListGremlinQueries(ctx context.Context, params *neptunedata.ListGremlinQueriesInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListGremlinQueriesOutput, error)
	ListLoaderJobs(ctx context.Context, params *neptunedata.ListLoaderJobsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListLoaderJobsOutput, error)
	ListMLDataProcessingJobs(ctx context.Context, params *neptunedata.ListMLDataProcessingJobsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListMLDataProcessingJobsOutput, error)
	ListMLEndpoints(ctx context.Context, params *neptunedata.ListMLEndpointsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListMLEndpointsOutput, error)
	ListMLModelTrainingJobs(ctx context.Context, params *neptunedata.ListMLModelTrainingJobsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListMLModelTrainingJobsOutput, error)
	ListMLModelTransformJobs(ctx context.Context, params *neptunedata.ListMLModelTransformJobsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListMLModelTransformJobsOutput, error)
	ListOpenCypherQueries(ctx context.Context, params *neptunedata.ListOpenCypherQueriesInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ListOpenCypherQueriesOutput, error)
	ManagePropertygraphStatistics(ctx context.Context, params *neptunedata.ManagePropertygraphStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ManagePropertygraphStatisticsOutput, error)
	ManageSparqlStatistics(ctx context.Context, params *neptunedata.ManageSparqlStatisticsInput, optFns ...func(*neptunedata.Options)) (*neptunedata.ManageSparqlStatisticsOutput, error)
	StartLoaderJob(ctx context.Context, params *neptunedata.StartLoaderJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.StartLoaderJobOutput, error)
	StartMLDataProcessingJob(ctx context.Context, params *neptunedata.StartMLDataProcessingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.StartMLDataProcessingJobOutput, error)
	StartMLModelTrainingJob(ctx context.Context, params *neptunedata.StartMLModelTrainingJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.StartMLModelTrainingJobOutput, error)
	StartMLModelTransformJob(ctx context.Context, params *neptunedata.StartMLModelTransformJobInput, optFns ...func(*neptunedata.Options)) (*neptunedata.StartMLModelTransformJobOutput, error)
}
