// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/opensearchserverless"
)

// OpensearchserverlessClient ...
type OpensearchserverlessClient interface {
	Options() opensearchserverless.Options
	BatchGetCollection(ctx context.Context, params *opensearchserverless.BatchGetCollectionInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.BatchGetCollectionOutput, error)
	BatchGetEffectiveLifecyclePolicy(ctx context.Context, params *opensearchserverless.BatchGetEffectiveLifecyclePolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.BatchGetEffectiveLifecyclePolicyOutput, error)
	BatchGetLifecyclePolicy(ctx context.Context, params *opensearchserverless.BatchGetLifecyclePolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.BatchGetLifecyclePolicyOutput, error)
	BatchGetVpcEndpoint(ctx context.Context, params *opensearchserverless.BatchGetVpcEndpointInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.BatchGetVpcEndpointOutput, error)
	CreateAccessPolicy(ctx context.Context, params *opensearchserverless.CreateAccessPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateAccessPolicyOutput, error)
	CreateCollection(ctx context.Context, params *opensearchserverless.CreateCollectionInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateCollectionOutput, error)
	CreateLifecyclePolicy(ctx context.Context, params *opensearchserverless.CreateLifecyclePolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateLifecyclePolicyOutput, error)
	CreateSecurityConfig(ctx context.Context, params *opensearchserverless.CreateSecurityConfigInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateSecurityConfigOutput, error)
	CreateSecurityPolicy(ctx context.Context, params *opensearchserverless.CreateSecurityPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateSecurityPolicyOutput, error)
	CreateVpcEndpoint(ctx context.Context, params *opensearchserverless.CreateVpcEndpointInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.CreateVpcEndpointOutput, error)
	DeleteAccessPolicy(ctx context.Context, params *opensearchserverless.DeleteAccessPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteAccessPolicyOutput, error)
	DeleteCollection(ctx context.Context, params *opensearchserverless.DeleteCollectionInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteCollectionOutput, error)
	DeleteLifecyclePolicy(ctx context.Context, params *opensearchserverless.DeleteLifecyclePolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteLifecyclePolicyOutput, error)
	DeleteSecurityConfig(ctx context.Context, params *opensearchserverless.DeleteSecurityConfigInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteSecurityConfigOutput, error)
	DeleteSecurityPolicy(ctx context.Context, params *opensearchserverless.DeleteSecurityPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteSecurityPolicyOutput, error)
	DeleteVpcEndpoint(ctx context.Context, params *opensearchserverless.DeleteVpcEndpointInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.DeleteVpcEndpointOutput, error)
	GetAccessPolicy(ctx context.Context, params *opensearchserverless.GetAccessPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.GetAccessPolicyOutput, error)
	GetAccountSettings(ctx context.Context, params *opensearchserverless.GetAccountSettingsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.GetAccountSettingsOutput, error)
	GetPoliciesStats(ctx context.Context, params *opensearchserverless.GetPoliciesStatsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.GetPoliciesStatsOutput, error)
	GetSecurityConfig(ctx context.Context, params *opensearchserverless.GetSecurityConfigInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.GetSecurityConfigOutput, error)
	GetSecurityPolicy(ctx context.Context, params *opensearchserverless.GetSecurityPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.GetSecurityPolicyOutput, error)
	ListAccessPolicies(ctx context.Context, params *opensearchserverless.ListAccessPoliciesInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListAccessPoliciesOutput, error)
	ListCollections(ctx context.Context, params *opensearchserverless.ListCollectionsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListCollectionsOutput, error)
	ListLifecyclePolicies(ctx context.Context, params *opensearchserverless.ListLifecyclePoliciesInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListLifecyclePoliciesOutput, error)
	ListSecurityConfigs(ctx context.Context, params *opensearchserverless.ListSecurityConfigsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListSecurityConfigsOutput, error)
	ListSecurityPolicies(ctx context.Context, params *opensearchserverless.ListSecurityPoliciesInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListSecurityPoliciesOutput, error)
	ListTagsForResource(ctx context.Context, params *opensearchserverless.ListTagsForResourceInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListTagsForResourceOutput, error)
	ListVpcEndpoints(ctx context.Context, params *opensearchserverless.ListVpcEndpointsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.ListVpcEndpointsOutput, error)
	TagResource(ctx context.Context, params *opensearchserverless.TagResourceInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *opensearchserverless.UntagResourceInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UntagResourceOutput, error)
	UpdateAccessPolicy(ctx context.Context, params *opensearchserverless.UpdateAccessPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateAccessPolicyOutput, error)
	UpdateAccountSettings(ctx context.Context, params *opensearchserverless.UpdateAccountSettingsInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateAccountSettingsOutput, error)
	UpdateCollection(ctx context.Context, params *opensearchserverless.UpdateCollectionInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateCollectionOutput, error)
	UpdateLifecyclePolicy(ctx context.Context, params *opensearchserverless.UpdateLifecyclePolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateLifecyclePolicyOutput, error)
	UpdateSecurityConfig(ctx context.Context, params *opensearchserverless.UpdateSecurityConfigInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateSecurityConfigOutput, error)
	UpdateSecurityPolicy(ctx context.Context, params *opensearchserverless.UpdateSecurityPolicyInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateSecurityPolicyOutput, error)
	UpdateVpcEndpoint(ctx context.Context, params *opensearchserverless.UpdateVpcEndpointInput, optFns ...func(*opensearchserverless.Options)) (*opensearchserverless.UpdateVpcEndpointOutput, error)
}
