// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/pcaconnectorad"
)

// PcaconnectoradClient ...
type PcaconnectoradClient interface {
	Options() pcaconnectorad.Options
	CreateConnector(ctx context.Context, params *pcaconnectorad.CreateConnectorInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.CreateConnectorOutput, error)
	CreateDirectoryRegistration(ctx context.Context, params *pcaconnectorad.CreateDirectoryRegistrationInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.CreateDirectoryRegistrationOutput, error)
	CreateServicePrincipalName(ctx context.Context, params *pcaconnectorad.CreateServicePrincipalNameInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.CreateServicePrincipalNameOutput, error)
	CreateTemplate(ctx context.Context, params *pcaconnectorad.CreateTemplateInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.CreateTemplateOutput, error)
	CreateTemplateGroupAccessControlEntry(ctx context.Context, params *pcaconnectorad.CreateTemplateGroupAccessControlEntryInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.CreateTemplateGroupAccessControlEntryOutput, error)
	DeleteConnector(ctx context.Context, params *pcaconnectorad.DeleteConnectorInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.DeleteConnectorOutput, error)
	DeleteDirectoryRegistration(ctx context.Context, params *pcaconnectorad.DeleteDirectoryRegistrationInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.DeleteDirectoryRegistrationOutput, error)
	DeleteServicePrincipalName(ctx context.Context, params *pcaconnectorad.DeleteServicePrincipalNameInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.DeleteServicePrincipalNameOutput, error)
	DeleteTemplate(ctx context.Context, params *pcaconnectorad.DeleteTemplateInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.DeleteTemplateOutput, error)
	DeleteTemplateGroupAccessControlEntry(ctx context.Context, params *pcaconnectorad.DeleteTemplateGroupAccessControlEntryInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.DeleteTemplateGroupAccessControlEntryOutput, error)
	GetConnector(ctx context.Context, params *pcaconnectorad.GetConnectorInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.GetConnectorOutput, error)
	GetDirectoryRegistration(ctx context.Context, params *pcaconnectorad.GetDirectoryRegistrationInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.GetDirectoryRegistrationOutput, error)
	GetServicePrincipalName(ctx context.Context, params *pcaconnectorad.GetServicePrincipalNameInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.GetServicePrincipalNameOutput, error)
	GetTemplate(ctx context.Context, params *pcaconnectorad.GetTemplateInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.GetTemplateOutput, error)
	GetTemplateGroupAccessControlEntry(ctx context.Context, params *pcaconnectorad.GetTemplateGroupAccessControlEntryInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.GetTemplateGroupAccessControlEntryOutput, error)
	ListConnectors(ctx context.Context, params *pcaconnectorad.ListConnectorsInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListConnectorsOutput, error)
	ListDirectoryRegistrations(ctx context.Context, params *pcaconnectorad.ListDirectoryRegistrationsInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListDirectoryRegistrationsOutput, error)
	ListServicePrincipalNames(ctx context.Context, params *pcaconnectorad.ListServicePrincipalNamesInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListServicePrincipalNamesOutput, error)
	ListTagsForResource(ctx context.Context, params *pcaconnectorad.ListTagsForResourceInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListTagsForResourceOutput, error)
	ListTemplateGroupAccessControlEntries(ctx context.Context, params *pcaconnectorad.ListTemplateGroupAccessControlEntriesInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListTemplateGroupAccessControlEntriesOutput, error)
	ListTemplates(ctx context.Context, params *pcaconnectorad.ListTemplatesInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.ListTemplatesOutput, error)
	TagResource(ctx context.Context, params *pcaconnectorad.TagResourceInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *pcaconnectorad.UntagResourceInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.UntagResourceOutput, error)
	UpdateTemplate(ctx context.Context, params *pcaconnectorad.UpdateTemplateInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.UpdateTemplateOutput, error)
	UpdateTemplateGroupAccessControlEntry(ctx context.Context, params *pcaconnectorad.UpdateTemplateGroupAccessControlEntryInput, optFns ...func(*pcaconnectorad.Options)) (*pcaconnectorad.UpdateTemplateGroupAccessControlEntryOutput, error)
}
