// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi"
)

// ResourcegroupstaggingapiClient ...
type ResourcegroupstaggingapiClient interface {
	Options() resourcegroupstaggingapi.Options
	DescribeReportCreation(ctx context.Context, params *resourcegroupstaggingapi.DescribeReportCreationInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.DescribeReportCreationOutput, error)
	GetComplianceSummary(ctx context.Context, params *resourcegroupstaggingapi.GetComplianceSummaryInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.GetComplianceSummaryOutput, error)
	GetResources(ctx context.Context, params *resourcegroupstaggingapi.GetResourcesInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.GetResourcesOutput, error)
	GetTagKeys(ctx context.Context, params *resourcegroupstaggingapi.GetTagKeysInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.GetTagKeysOutput, error)
	GetTagValues(ctx context.Context, params *resourcegroupstaggingapi.GetTagValuesInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.GetTagValuesOutput, error)
	StartReportCreation(ctx context.Context, params *resourcegroupstaggingapi.StartReportCreationInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.StartReportCreationOutput, error)
	TagResources(ctx context.Context, params *resourcegroupstaggingapi.TagResourcesInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.TagResourcesOutput, error)
	UntagResources(ctx context.Context, params *resourcegroupstaggingapi.UntagResourcesInput, optFns ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.UntagResourcesOutput, error)
}
