// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ssmcontacts"
)

// SsmcontactsClient ...
type SsmcontactsClient interface {
	Options() ssmcontacts.Options
	AcceptPage(ctx context.Context, params *ssmcontacts.AcceptPageInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.AcceptPageOutput, error)
	ActivateContactChannel(ctx context.Context, params *ssmcontacts.ActivateContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ActivateContactChannelOutput, error)
	CreateContact(ctx context.Context, params *ssmcontacts.CreateContactInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.CreateContactOutput, error)
	CreateContactChannel(ctx context.Context, params *ssmcontacts.CreateContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.CreateContactChannelOutput, error)
	CreateRotation(ctx context.Context, params *ssmcontacts.CreateRotationInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.CreateRotationOutput, error)
	CreateRotationOverride(ctx context.Context, params *ssmcontacts.CreateRotationOverrideInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.CreateRotationOverrideOutput, error)
	DeactivateContactChannel(ctx context.Context, params *ssmcontacts.DeactivateContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DeactivateContactChannelOutput, error)
	DeleteContact(ctx context.Context, params *ssmcontacts.DeleteContactInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DeleteContactOutput, error)
	DeleteContactChannel(ctx context.Context, params *ssmcontacts.DeleteContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DeleteContactChannelOutput, error)
	DeleteRotation(ctx context.Context, params *ssmcontacts.DeleteRotationInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DeleteRotationOutput, error)
	DeleteRotationOverride(ctx context.Context, params *ssmcontacts.DeleteRotationOverrideInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DeleteRotationOverrideOutput, error)
	DescribeEngagement(ctx context.Context, params *ssmcontacts.DescribeEngagementInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DescribeEngagementOutput, error)
	DescribePage(ctx context.Context, params *ssmcontacts.DescribePageInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.DescribePageOutput, error)
	GetContact(ctx context.Context, params *ssmcontacts.GetContactInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.GetContactOutput, error)
	GetContactChannel(ctx context.Context, params *ssmcontacts.GetContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.GetContactChannelOutput, error)
	GetContactPolicy(ctx context.Context, params *ssmcontacts.GetContactPolicyInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.GetContactPolicyOutput, error)
	GetRotation(ctx context.Context, params *ssmcontacts.GetRotationInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.GetRotationOutput, error)
	GetRotationOverride(ctx context.Context, params *ssmcontacts.GetRotationOverrideInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.GetRotationOverrideOutput, error)
	ListContactChannels(ctx context.Context, params *ssmcontacts.ListContactChannelsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListContactChannelsOutput, error)
	ListContacts(ctx context.Context, params *ssmcontacts.ListContactsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListContactsOutput, error)
	ListEngagements(ctx context.Context, params *ssmcontacts.ListEngagementsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListEngagementsOutput, error)
	ListPageReceipts(ctx context.Context, params *ssmcontacts.ListPageReceiptsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListPageReceiptsOutput, error)
	ListPageResolutions(ctx context.Context, params *ssmcontacts.ListPageResolutionsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListPageResolutionsOutput, error)
	ListPagesByContact(ctx context.Context, params *ssmcontacts.ListPagesByContactInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListPagesByContactOutput, error)
	ListPagesByEngagement(ctx context.Context, params *ssmcontacts.ListPagesByEngagementInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListPagesByEngagementOutput, error)
	ListPreviewRotationShifts(ctx context.Context, params *ssmcontacts.ListPreviewRotationShiftsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListPreviewRotationShiftsOutput, error)
	ListRotationOverrides(ctx context.Context, params *ssmcontacts.ListRotationOverridesInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListRotationOverridesOutput, error)
	ListRotationShifts(ctx context.Context, params *ssmcontacts.ListRotationShiftsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListRotationShiftsOutput, error)
	ListRotations(ctx context.Context, params *ssmcontacts.ListRotationsInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListRotationsOutput, error)
	ListTagsForResource(ctx context.Context, params *ssmcontacts.ListTagsForResourceInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.ListTagsForResourceOutput, error)
	PutContactPolicy(ctx context.Context, params *ssmcontacts.PutContactPolicyInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.PutContactPolicyOutput, error)
	SendActivationCode(ctx context.Context, params *ssmcontacts.SendActivationCodeInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.SendActivationCodeOutput, error)
	StartEngagement(ctx context.Context, params *ssmcontacts.StartEngagementInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.StartEngagementOutput, error)
	StopEngagement(ctx context.Context, params *ssmcontacts.StopEngagementInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.StopEngagementOutput, error)
	TagResource(ctx context.Context, params *ssmcontacts.TagResourceInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *ssmcontacts.UntagResourceInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.UntagResourceOutput, error)
	UpdateContact(ctx context.Context, params *ssmcontacts.UpdateContactInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.UpdateContactOutput, error)
	UpdateContactChannel(ctx context.Context, params *ssmcontacts.UpdateContactChannelInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.UpdateContactChannelOutput, error)
	UpdateRotation(ctx context.Context, params *ssmcontacts.UpdateRotationInput, optFns ...func(*ssmcontacts.Options)) (*ssmcontacts.UpdateRotationOutput, error)
}
