// Code generated by ifacemaker; DO NOT EDIT.

package service

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/xray"
)

// XrayClient ...
type XrayClient interface {
	Options() xray.Options
	BatchGetTraces(ctx context.Context, params *xray.BatchGetTracesInput, optFns ...func(*xray.Options)) (*xray.BatchGetTracesOutput, error)
	CreateGroup(ctx context.Context, params *xray.CreateGroupInput, optFns ...func(*xray.Options)) (*xray.CreateGroupOutput, error)
	CreateSamplingRule(ctx context.Context, params *xray.CreateSamplingRuleInput, optFns ...func(*xray.Options)) (*xray.CreateSamplingRuleOutput, error)
	DeleteGroup(ctx context.Context, params *xray.DeleteGroupInput, optFns ...func(*xray.Options)) (*xray.DeleteGroupOutput, error)
	DeleteResourcePolicy(ctx context.Context, params *xray.DeleteResourcePolicyInput, optFns ...func(*xray.Options)) (*xray.DeleteResourcePolicyOutput, error)
	DeleteSamplingRule(ctx context.Context, params *xray.DeleteSamplingRuleInput, optFns ...func(*xray.Options)) (*xray.DeleteSamplingRuleOutput, error)
	GetEncryptionConfig(ctx context.Context, params *xray.GetEncryptionConfigInput, optFns ...func(*xray.Options)) (*xray.GetEncryptionConfigOutput, error)
	GetGroup(ctx context.Context, params *xray.GetGroupInput, optFns ...func(*xray.Options)) (*xray.GetGroupOutput, error)
	GetGroups(ctx context.Context, params *xray.GetGroupsInput, optFns ...func(*xray.Options)) (*xray.GetGroupsOutput, error)
	GetInsight(ctx context.Context, params *xray.GetInsightInput, optFns ...func(*xray.Options)) (*xray.GetInsightOutput, error)
	GetInsightEvents(ctx context.Context, params *xray.GetInsightEventsInput, optFns ...func(*xray.Options)) (*xray.GetInsightEventsOutput, error)
	GetInsightImpactGraph(ctx context.Context, params *xray.GetInsightImpactGraphInput, optFns ...func(*xray.Options)) (*xray.GetInsightImpactGraphOutput, error)
	GetInsightSummaries(ctx context.Context, params *xray.GetInsightSummariesInput, optFns ...func(*xray.Options)) (*xray.GetInsightSummariesOutput, error)
	GetSamplingRules(ctx context.Context, params *xray.GetSamplingRulesInput, optFns ...func(*xray.Options)) (*xray.GetSamplingRulesOutput, error)
	GetSamplingStatisticSummaries(ctx context.Context, params *xray.GetSamplingStatisticSummariesInput, optFns ...func(*xray.Options)) (*xray.GetSamplingStatisticSummariesOutput, error)
	GetSamplingTargets(ctx context.Context, params *xray.GetSamplingTargetsInput, optFns ...func(*xray.Options)) (*xray.GetSamplingTargetsOutput, error)
	GetServiceGraph(ctx context.Context, params *xray.GetServiceGraphInput, optFns ...func(*xray.Options)) (*xray.GetServiceGraphOutput, error)
	GetTimeSeriesServiceStatistics(ctx context.Context, params *xray.GetTimeSeriesServiceStatisticsInput, optFns ...func(*xray.Options)) (*xray.GetTimeSeriesServiceStatisticsOutput, error)
	GetTraceGraph(ctx context.Context, params *xray.GetTraceGraphInput, optFns ...func(*xray.Options)) (*xray.GetTraceGraphOutput, error)
	GetTraceSummaries(ctx context.Context, params *xray.GetTraceSummariesInput, optFns ...func(*xray.Options)) (*xray.GetTraceSummariesOutput, error)
	ListResourcePolicies(ctx context.Context, params *xray.ListResourcePoliciesInput, optFns ...func(*xray.Options)) (*xray.ListResourcePoliciesOutput, error)
	ListTagsForResource(ctx context.Context, params *xray.ListTagsForResourceInput, optFns ...func(*xray.Options)) (*xray.ListTagsForResourceOutput, error)
	PutEncryptionConfig(ctx context.Context, params *xray.PutEncryptionConfigInput, optFns ...func(*xray.Options)) (*xray.PutEncryptionConfigOutput, error)
	PutResourcePolicy(ctx context.Context, params *xray.PutResourcePolicyInput, optFns ...func(*xray.Options)) (*xray.PutResourcePolicyOutput, error)
	PutTelemetryRecords(ctx context.Context, params *xray.PutTelemetryRecordsInput, optFns ...func(*xray.Options)) (*xray.PutTelemetryRecordsOutput, error)
	PutTraceSegments(ctx context.Context, params *xray.PutTraceSegmentsInput, optFns ...func(*xray.Options)) (*xray.PutTraceSegmentsOutput, error)
	TagResource(ctx context.Context, params *xray.TagResourceInput, optFns ...func(*xray.Options)) (*xray.TagResourceOutput, error)
	UntagResource(ctx context.Context, params *xray.UntagResourceInput, optFns ...func(*xray.Options)) (*xray.UntagResourceOutput, error)
	UpdateGroup(ctx context.Context, params *xray.UpdateGroupInput, optFns ...func(*xray.Options)) (*xray.UpdateGroupOutput, error)
	UpdateSamplingRule(ctx context.Context, params *xray.UpdateSamplingRuleInput, optFns ...func(*xray.Options)) (*xray.UpdateSamplingRuleOutput, error)
}
