// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	appconfigdata "github.com/aws/aws-sdk-go-v2/service/appconfigdata"

	mock "github.com/stretchr/testify/mock"
)

// AppconfigdataClient is an autogenerated mock type for the AppconfigdataClient type
type AppconfigdataClient struct {
	mock.Mock
}

// GetLatestConfiguration provides a mock function with given fields: ctx, params, optFns
func (_m *AppconfigdataClient) GetLatestConfiguration(ctx context.Context, params *appconfigdata.GetLatestConfigurationInput, optFns ...func(*appconfigdata.Options)) (*appconfigdata.GetLatestConfigurationOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestConfiguration")
	}

	var r0 *appconfigdata.GetLatestConfigurationOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *appconfigdata.GetLatestConfigurationInput, ...func(*appconfigdata.Options)) (*appconfigdata.GetLatestConfigurationOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *appconfigdata.GetLatestConfigurationInput, ...func(*appconfigdata.Options)) *appconfigdata.GetLatestConfigurationOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appconfigdata.GetLatestConfigurationOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *appconfigdata.GetLatestConfigurationInput, ...func(*appconfigdata.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Options provides a mock function with given fields:
func (_m *AppconfigdataClient) Options() appconfigdata.Options {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 appconfigdata.Options
	if rf, ok := ret.Get(0).(func() appconfigdata.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(appconfigdata.Options)
	}

	return r0
}

// StartConfigurationSession provides a mock function with given fields: ctx, params, optFns
func (_m *AppconfigdataClient) StartConfigurationSession(ctx context.Context, params *appconfigdata.StartConfigurationSessionInput, optFns ...func(*appconfigdata.Options)) (*appconfigdata.StartConfigurationSessionOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StartConfigurationSession")
	}

	var r0 *appconfigdata.StartConfigurationSessionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *appconfigdata.StartConfigurationSessionInput, ...func(*appconfigdata.Options)) (*appconfigdata.StartConfigurationSessionOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *appconfigdata.StartConfigurationSessionInput, ...func(*appconfigdata.Options)) *appconfigdata.StartConfigurationSessionOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appconfigdata.StartConfigurationSessionOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *appconfigdata.StartConfigurationSessionInput, ...func(*appconfigdata.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppconfigdataClient creates a new instance of AppconfigdataClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppconfigdataClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppconfigdataClient {
	mock := &AppconfigdataClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
