// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	eksauth "github.com/aws/aws-sdk-go-v2/service/eksauth"
	mock "github.com/stretchr/testify/mock"
)

// EksauthClient is an autogenerated mock type for the EksauthClient type
type EksauthClient struct {
	mock.Mock
}

// AssumeRoleForPodIdentity provides a mock function with given fields: ctx, params, optFns
func (_m *EksauthClient) AssumeRoleForPodIdentity(ctx context.Context, params *eksauth.AssumeRoleForPodIdentityInput, optFns ...func(*eksauth.Options)) (*eksauth.AssumeRoleForPodIdentityOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssumeRoleForPodIdentity")
	}

	var r0 *eksauth.AssumeRoleForPodIdentityOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eksauth.AssumeRoleForPodIdentityInput, ...func(*eksauth.Options)) (*eksauth.AssumeRoleForPodIdentityOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eksauth.AssumeRoleForPodIdentityInput, ...func(*eksauth.Options)) *eksauth.AssumeRoleForPodIdentityOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eksauth.AssumeRoleForPodIdentityOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eksauth.AssumeRoleForPodIdentityInput, ...func(*eksauth.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Options provides a mock function with given fields:
func (_m *EksauthClient) Options() eksauth.Options {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 eksauth.Options
	if rf, ok := ret.Get(0).(func() eksauth.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(eksauth.Options)
	}

	return r0
}

// NewEksauthClient creates a new instance of EksauthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEksauthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EksauthClient {
	mock := &EksauthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
